### ISSUE TITLE
User case

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#100]
Hi,
Hopefully you can help.
I have a scenario where a user is asking to withdraw permissions on the deviceID. In the android settings one can withdraw access to phone and prevent notifications, but I see no permissions for deviceID. Do you know if this is possible? Am I correct in thinking that if you prevent notifications, thats also related to the device ID.

Thanks in advance.

**Comment by rlepinski** [comment]
What device ID are you talking about? 

Also, notifications do not need any permissions to display, but they can be opted out at the app level in the system settings or through Android O channels/categories.
