### ISSUE TITLE
[1.6.0] Push clicked: how to differentiate if app was closed or in background?

### ISSUE THREAD

**Issue by OrianeInMoon** [urbanairship/react-native-module#103]
Hi,

Two scenarios: (tested on iOS)

1 ) App is **closed**, notification is clicked by the user, app opens and logs `isForeground` to `true`
2 ) App is **opened, but in background**,  notification is clicked by the user, app pass to the foreground and logs `isForeground` to `true`

Both scenarios give the same logs, ** I'm not able to isolate one of the two scenarios, any idea??
Thanks

_______________

```json
"react-native": "0.53.3",
"urbanairship-react-native": "^1.6.0",
```

**Comment by rlepinski** [comment]
The `isForeground` is to determine if its a foreground notification response (will start the app). Closed -> Foreground vs Background -> Foreground is not exposed anywhere in our plugin. You will have to track app state within your app.

What are you trying to accomplish?

**Comment by OrianeInMoon** [comment]
@rlepinski I want to know if app was "closed" or "in background" within the `notificationResponse` event.
From my tests understanding, `pushReceived` will be triggered when app is opened right?

**Comment by rlepinski** [comment]
Why do you need to know the difference? Either case they arrived into your app through a notification. Apples and Android do not make it easy to detect closed vs background, so we would have to do the same thing that you could do within the app by tracking state.

Push received will be called on iOS when the app is in the foreground OR if you send a content-available push

**Comment by OrianeInMoon** [comment]
@rlepinski thanks for explanations. 

Imagine a push notification with a link in it (example: `chat/1`)

- If app closed
Notification click > start > auth evaluation > redirect to `chat/1`

- If app in background
Notification click > foreground > auth evaluation > **propose** to redirect to `chat/1`.
(In this case we don't want to make an intempestive redirection (if user was filling a form for instance))

What do you think about this use case? (I know there is deep linking, but we already integrate our push redirections like that in cordova, and we desire to use the same logic with this module).

- - - 

About "tracking the app state within the app", the trick would be to add an UA event in an app "onResume" event or something like that?

**Comment by rlepinski** [comment]
@OrianeInMoon Can you have a app state flag "promptRedirect" that you can set after the user takes action in the app? 

We can look into adding a flag for "launched from push", but iOS and Android dont really expose that in a reliable way.

**Comment by athondapu** [comment]
> @rlepinski thanks for explanations.
> 
> Imagine a push notification with a link in it (example: `chat/1`)
> 
> * If app closed
>   Notification click > start > auth evaluation > redirect to `chat/1`
> * If app in background
>   Notification click > foreground > auth evaluation > **propose** to redirect to `chat/1`.
>   (In this case we don't want to make an intempestive redirection (if user was filling a form for instance))
> 
> What do you think about this use case? (I know there is deep linking, but we already integrate our push redirections like that in cordova, and we desire to use the same logic with this module).
> 
> About "tracking the app state within the app", the trick would be to add an UA event in an app "onResume" event or something like that?

@OrianeInMoon I too have the same requirement. Here is my app works when ever you opens an app it authenticate first and navigate to Home screen. 
Now , I just send the notification and I closed my app. When I click on the notification, first it's authenticates and then redirect to home screen but its not redirecting to my actual notification screen. I wrote a code like if you click notification redirects to that edit screen.

Have you solved this issue in your app.? If yes, can you please tell me the way.?
