### ISSUE TITLE
Issue when enabling notifications on iOS

### ISSUE THREAD

**Issue by jortegano** [urbanairship/react-native-module#104]
Hi, I'm having a weird behavior when trying to enable user notifications on iOS.

I'm enabling the notifications in `componentDidMount` in the root container of my app. The issue is that this is not working properly on every installation of the app. Sometimes the notifications activation popup is shown in the first run of the app(as it should be!), sometimes in the second run...and sometimes the app never shows the pop up and in consequence there is no way to activate them and the app doesn't receive any notifications.

The only way I found to actually fire the notification activation process on every installation is to call `UrbanAirship.setUserNotificationsEnabled(true)` with some delay; currently I'm using a timer in order to fire the process 3 seconds after the `componentDidMount` is called.

It seems that if I call the process for enabling notifications right away in the `componentDidMount` something is still not loaded and that makes the process to fail sometimes.

Is this the correct behavior? Are there any known issues or conflicts with other react native plugins that could generate this weird behavior?

I'm really interested in finding an explanation to this behavior; even though, my current solution seems to work fine, it's kind of a hack and I would like to avoid difficult to track issues in the future.

Versions:
React-Native: 0.53.3
urbanairship-react-native: 1.6.0
UrbanAirship-iOS-SDK: 9.0.4
iOS versions: 10+ and 11+

Thanks for your help, Jose.

**Comment by rlepinski** [comment]
I am not sure why that is happening, we can take a look.

**Comment by marc-scig** [comment]
Hi @jortegano,

Any chance you could share a snippet of your root component code to give us a better sense of what might be going on?

**Comment by marc-scig** [comment]
For what it's worth, I've tried to reproduce what you're describing with our sample app, but everything appears to be working normally. I assume that when installing you're fully deleting the app before reinstalling (iOS doesn't prompt unless it's a true first run, regardless of whether the app has changed).

I should also add that we don't really recommend enabling push automatically like this. The best practice is to give users the opportunity to enable it themselves, either directly or indirectly, through the UI. This would also solve your problem, though it would still be helpful to see how you're integrating the module in case there's any additional advice we can give, or in the off chance that there's something weird going on with the module itself.

**Comment by marc-scig** [comment]
I'm going to close this out, but if you have any additional questions or problems, please contact support. Thanks!

**Comment by Jahans3** [comment]
@jortegano do you mind sharing your code? I'm unable to get this to work even with a delay
