### ISSUE TITLE
Android app crashing when notification received

### ISSUE THREAD

**Issue by willbach** [urbanairship/react-native-module#106]
React Native: 0.50.8
UAReactNative: 1.6.0
Urban Airship SDK: 9.0.3

Hello, my android app is crashing when I receive a push notification. The specific error is coming from the Android SDK. Here is the error log:

04-10 16:53:12.740 24249 24420 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method setChannelId(Ljava/lang/String;)Landroid/support/v4/app/NotificationCompat$Builder; in class Landroid/support/v4/app/NotificationCompat$Builder; or its super classes (declaration of 'android.support.v4.app.NotificationCompat$Builder' appears in /data/app/com.lndr-5AXQI6xACUdoJo4_EUOE5A==/base.apk)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at com.urbanairship.push.notifications.NotificationFactory.createNotificationBuilder(NotificationFactory.java:345)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at com.urbanairship.push.notifications.DefaultNotificationFactory.createNotification(DefaultNotificationFactory.java:59)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at com.urbanairship.push.IncomingPushRunnable.displayNotification(IncomingPushRunnable.java:254)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at com.urbanairship.push.IncomingPushRunnable.processPush(IncomingPushRunnable.java:169)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at com.urbanairship.push.IncomingPushRunnable.run(IncomingPushRunnable.java:81)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
04-10 16:53:12.740 24249 24420 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)

From what I can find on this issue, it seems to be a problem with Android 8.0 and higher, but I was unable to find any solutions that successfully resolve the problem. Please let me know if you've seen this before, thanks!

**Comment by rlepinski** [comment]
You need to set the `compileSdkVersion` to 27 in your app's build.gradle file.

**Comment by willbach** [comment]
Thank you! I wasn't matching the buildToolsVersion correctly.

**Comment by willbach** [comment]
Hello again,

I closed this prematurely after the app didn't crash on the first test push notification. Since then I have had the same issue every time I push a notification to the app. I have tested with the UA test push UI and my server. I am using a Pixel XL with Android 8.1.0. Here are the settings in my app-level build.gradle file:

compileSdkVersion 27
buildToolsVersion "27.0.3"
minSdkVersion 18
targetSdkVersion 27

I have tried clearing and reinstalling node modules but always get the same behavior. I am connected to my regular cell network. If you have any additional suggestions it would be very appreciated.

**Comment by rlepinski** [comment]
@willbach Did you figure it out? Looks like the original crash was not from compileSdkVersion as I first thought, but actually an older version of the support library. If you still need help could you post your build.gradle files?

**Comment by willbach** [comment]
@rlepinski I eventually figured it out. Changing the compileSdkVersion was the first part of it, and from there I had to update all of the libraries and build tools involved. I inherited this project from someone else who had been using outdated build tools.
