### ISSUE TITLE
Undefined is not an object UrbanAirshipModule.setUserNotificationsEnabled

### ISSUE THREAD

**Issue by cvongrim** [urbanairship/react-native-module#107]
I am having trouble getting this running. I have followed the instructions and it the module seems to be partially working.

I have installed the module, linked it and created the airshipconfig.properties on Android. If I do not add the line ` UrbanAirship.setUserNotificationsEnabled(true);` and send a push notification I see in the logs that UALIB: Received Push, UALIB: User notifications opted out and UALib: ReactAirshipReceiver - Received intent with action. This leads me to believe everything is linked.

However, once I add ` UrbanAirship.setUserNotificationsEnabled(true);` and import the library `import {UrbanAirship, UACustomEvent} from 'urbanairship-react-native';` I get an error that setUserNotificationsEnabled is undefined.

I have tried placing `setUserNotificationsEnabled ()` in the constructor and componentWillMount.

I am using RN 0.53.0 and react 16.2.0.

**Comment by crow** [comment]
Are you able to produce this same behavior when you enable notifications in the provided sample? The sample provides a useful platform to test this kind of issue.

**Comment by crow** [comment]
It looks like there is a difference in behavior with newer versions of react-native - looking into this.

**Comment by cvongrim** [comment]
Incase someone stumbles into the same issue. It looks like the react-native link command did not add `ReactAirshipPackage()` to my MainApplication.java file. Adding that resolved the issue.

**Comment by otusweb** [comment]
I had the same issue. Would it be possible to add something to the doc with what the manual step need to be. I had to dig through the sample to figure out what to add to my MainApplication.java.

For those who come here later:

    import com.urbanairship.reactnative.ReactAirshipPackage;

and 


    @Override
     protected List<ReactPackage> getPackages() {
       return Arrays.<ReactPackage>asList(
           new MainReactPackage(),
             new ReactAirshipPackage()
       );
     }
