### ISSUE TITLE
iOS issue 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by Zak-JS** [urbanairship/react-native-module#109]
As the title suggests, I can't seem to get the xcode project to build after including the urbanairship SDK in the podfile of my react native project. I've followed the instructions UA RN docs over at https://docs.urbanairship.com/platform/react-native/ &  I'm using RN26.0

Any ideas to resolve this would be greatly appreciated as this is blocking our integration with UrbanAirship.

**Comment by crow** [comment]
The current Urban Airship module requires react-native 0.44.0 and above.

[README](https://github.com/urbanairship/react-native-module/blob/master/README.md)

**Comment by Zak-JS** [comment]
sorry that was actually a mistake, no idea where I got 26 from, we're actually using the latest version of RN (55)

**Comment by rlepinski** [comment]
@Zak-JS Does not sound like an issue with our SDK, but more so with a misconfigured xcode project. Take a look at this issue - https://github.com/facebook/react-native/issues/13371. You have to serialize the build order on react projects or react can fail to build.
