### ISSUE TITLE
ClassNotFoundException in Android with Support Library 27

### ISSUE THREAD

**Issue by santoslucas** [urbanairship/react-native-module#110]
AsyncTaskCompat has been removed in support library 27 but it's being used in UrbanAirshipReactModule.java.

After updating the support library in our project we are receiving a ClassNotFoundException.

**Comment by rlepinski** [comment]
Yep, you are right. Will fix today or Friday.

**Comment by rlepinski** [comment]
Fixed in 1.6.2

**Comment by santoslucas** [comment]
Will you release de new version in npm soon?

**Comment by rlepinski** [comment]
@santoslucas My mistake, I did not update the package.json so the promotion failed due to it still be versioned as 1.6.1. Should be ready - https://www.npmjs.com/package/urbanairship-react-native
