### ISSUE TITLE
Urban Airship overwrites session in keychain

### ISSUE THREAD

**Issue by jacobcabantomski-ct** [urbanairship/react-native-module#114]
Not sure if this belongs here or in https://github.com/urbanairship/ios-library

We are using https://github.com/oblador/react-native-keychain to store session information for our react-native app.

```
 import * as Keychain from 'react-native-keychain';

...

const token = 'someJWT';
await Keychain.setGenericPassword('session', token);

...

const token = await Keychain.getGenericPassword();
```

We recently added UrbanAirship to this app and noticed that on iOS `Keychain.getGenericPassword` is now returning a UUID v4 and not the expected JWT we stored. We believe this library is overriding that token with UrbanAirship's session ID.

We can change where we store that JWT token to not conflict with UrbanAirship, but it will invalidate all of our currently logged in mobile users. Is it possible to change/configure where this library is storing its session identifier?

**Comment by rlepinski** [comment]
It looks like we are not overriding the entry but instead `react-native-keychain` returns the first entry it finds in the keychain. If you look at the api you are using, `getGenericPassword` does not take in a user ID so its just returning the first `kSecClassGenericPassword` entry it finds in the keychain. Take a look here - https://github.com/oblador/react-native-keychain/issues/112. We are unable to resolve this issue on our side but instead you should comment on the issue.

For a workaround, you would need to write your own `getGenericPassword()` that takes in the user name and sets up the search query to look for the name.

**Comment by jacobcabantomski-ct** [comment]
Ah that makes sense, my mistake for putting this issue here. Thanks for the help and quick response @rlepinski
