### ISSUE TITLE
Android: Could not find any version that matches com.google.android.gms:play-services-gcm:[11.8.0,)

### ISSUE THREAD

**Issue by JuliusCosmoRomeo** [urbanairship/react-native-module#115]
After following your installation guide I ran `react-native run-android` and get the following error: 

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':urbanairship-react-native'.
      > Could not resolve all dependencies for configuration ':urbanairship-react-native:_debugPublishCopy'.
         > Could not find any version that matches com.google.android.gms:play-services-gcm:[11.8.0,).
           Versions that do not match:
               11.0.4
               11.0.2
               11.0.1
               11.0.0
               10.2.6
               + 18 more
           Searched in the following locations:
               file:/Users/julius/Library/Android/sdk/extras/google/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
               file:/Users/julius/Documents/my-project/android/sdk-manager/com/google/android/gms/play-services-gcm/maven-metadata.xml
               file:/Users/julius/Documents/my-project/android/sdk-manager/com/google/android/gms/play-services-gcm/
               file:/Users/julius/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/maven-metadata.xml
               file:/Users/julius/Library/Android/sdk/extras/android/m2repository/com/google/android/gms/play-services-gcm/
               file:/Users/julius/Documents/my-project/android/sdk-manager/com/google/android/gms/play-services-gcm/maven-metadata.xml
               file:/Users/julius/Documents/my-project/android/sdk-manager/com/google/android/gms/play-services-gcm/
           Required by:
               my-project:urbanairship-react-native:unspecified`

If I change the dependency version in the build.gradle file of the urbanairship module to one of those the compiler found the app compilates and installs but crashes instantly on start.

**Comment by rlepinski** [comment]
Same issue as https://github.com/urbanairship/react-native-module/issues/84

You need to add [google's maven repo ](https://developer.android.com/studio/build/dependencies.html#google-maven) to your repositories 

```
allprojects {
    repositories {
        google()

        // If you're using a version of Gradle lower than 4.1, you must instead use:
        // maven {
        //     url 'https://maven.google.com'
        // }
        // An alternative URL is 'https://dl.google.com/dl/android/maven2/'
    }
}
```
