### ISSUE TITLE
Android app crashes on launch

### ISSUE THREAD

**Issue by JuliusCosmoRomeo** [urbanairship/react-native-module#116]
Our app compiles and builds without complaining and then crashes on launch. 
I assumed this error would come from wrong compileSdkVersion or buildToolsVersion as some other people had similar problems but that didn't fix it yet. 
I have yet tested it with the following configurations:
compileSdkVersion | buildToolsVersion
27 | 27.0.3
26 | 26.0.2

**Comment by rlepinski** [comment]
I need the runtime crash to figure out whats going wrong. It should be part of your device logs using logcat. Most likely you have a mismatched version of google play services/firebase or an older version of support library. With the crash, please also provide the output of `./gradlew dependencies`. Contact support if you need more help.

**Comment by JuliusCosmoRomeo** [comment]
Just figured this out. When I set compileSdkVersion & buildToolsVersion to anything different than 23 | "23.0.1" ReactNativeMaps crashed. 
Fixed this by adding 

```compile(project(':react-native-maps')){
    exclude group: 'com.google.android.gms', module: 'play-services-base'
    exclude group: 'com.google.android.gms', module: 'play-services-maps'
  }
  compile 'com.google.android.gms:play-services-base:+'
  compile 'com.google.android.gms:play-services-maps:+'
```
according to [this](https://github.com/react-community/react-native-maps/issues/951) threads solution.
