### ISSUE TITLE
How can i Navigate Specific screen using Deeplink

### ISSUE THREAD

**Issue by lavarajallu** [urbanairship/react-native-module#120]
```
UrbanAirship.addListener("deepLink", (event) => {
  console.log('Deep link: ', event.deepLink);
});
```
How can we use this code ! to navigate exact Screen.
Here this code based how can we navigate specific screen. Where should i placed this code to perform navigation.

**Comment by rlepinski** [comment]
You can add the listener during `componentWillMount`. Use the deeplink to navigate to a specific screen:
```
UrbanAirship.addListener("deepLink", (event) => {
  if (event.deepLink === "screen1") {
      // navigate to screen1
  }
});
```

Please contact support for further help. Github issues are for issues/bugs with the plugin, not a place to request help.
