### ISSUE TITLE
Can't find keys for 'airshipconfig.properties' file.

### ISSUE THREAD

**Issue by ruk91** [urbanairship/react-native-module#124]
Please give instructions for update these keys. Thank you.

developmentAppKey = Your Development App Key
developmentAppSecret = Your Development App Secret
productionAppKey = Your Production App Key
productionAppSecret = Your Production Secret

gcmSender = Your GCM sender ID is your Google API project number (required for GCM)

**Comment by crow** [comment]
You get these keys from the go.urbanairship.com dashboard. 

Information about getting started on the go.urbanairship.com dashboard is available here:
https://docs.urbanairship.com/guides/getting-started-engage/

Information about creating your airship config can be found here:
https://docs.urbanairship.com/platform/android/#create-airship-config-options

If you need more help, please contact support@urbanairship.com

**Comment by ruk91** [comment]
@crow, thanks so much.
