### ISSUE TITLE
iOS 'React/RCTEventEmitter.h' file not found

### ISSUE THREAD

**Issue by wpconsulate** [urbanairship/react-native-module#128]
I detached an Expo project and using expo-kit to develop and I followed the instructions here https://docs.urbanairship.com/platform/react-native/ and installed the SDK. While building I'm getting this error http://prntscr.com/k61d3g. I tested the App working fine just before installing the UrbanAirship SDK, So, something for sure wrong with UrbanAirship SDK.

# Preliminary Info

### What Urban Airship dependencies are you using?
"urbanairship-react-native": "^1.6.2"
I have put in podfile 
`pod 'UrbanAirship-iOS-SDK', '~>9.0'`
and run the "pod install"

### What are the versions of any relevant development tools you are using?
My Package.json file looks like this

> {
>   "main": "node_modules/expo/AppEntry.js",
>   "private": true,
>   "dependencies": {
>     "expo": "^28.0.0",
>     "jsonq": "^1.1.0",
>     "moment": "^2.22.2",
>     "react": "16.3.1",
>     "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
>     "react-native-datepicker": "^1.7.2",
>     "react-native-device-info": "^0.21.5",
>     "react-native-elements": "^0.19.1",
>     "react-native-google-analytics": "^1.3.2",
>     "react-native-keyboard-aware-scroll-view": "^0.5.0",
>     "react-native-masked-text": "^1.7.2",
>     "react-native-picker-select": "^3.1.3",
>     "react-navigation": "^2.5.5",
>     "urbanairship-react-native": "^1.6.2"
>   }
> }

I tried building the react.xcodeproj Project itself and also tried building the Pods.xcodeproj project as well but no help there. Any suggestions would be appriciated.

### What unexpected behavior are you seeing?
iOS project build is failing

### What is the expected behavior?
iOS project should build as normal

### What are the steps to reproduce the unexpected behavior?
create a react native project with above packagaes and try installing the UrbanTitanium it'll break the build

### Do you have logging for the issue?
please refer to screenshot: http://prntscr.com/k61jxz

**Comment by rlepinski** [comment]
Duplicate of https://github.com/urbanairship/react-native-module/issues/109

Take a look at this issue - https://github.com/facebook/react-native/issues/13371. You have to serialize the build order on react projects or react can fail to build.

**Comment by wpconsulate** [comment]
I followed the same sequence but it didn't worked, So rather than closing the Issue you should help on resolving the issue. or you guys also have sort of targets? I see that thing happens a lot with my telecom operator. Sorry for that but I got that sense, as you can suggest me that so I could have replied that I have already tried that and no luck

**Comment by rlepinski** [comment]
What steps have you tried to resolve the issue? When I came across similar issues in our sample, I sometimes had to wipe the derived data and do a clean rebuild. Could you try that? Could you provide a sample project that helps us reproduce your issue? Any chance you could share your project?

**Comment by wpconsulate** [comment]
It worked for me after upgrading the expoKit Version so it was something related to ExpoKit Version in case project is detached from expo.

thanks for help :)

**Comment by nelsonchen5** [comment]
@wpconsulate tried your solution, and still had build failed on a freshly detached expo kit. Using expo 29.0.0 and added Urban Airship SDK
