### ISSUE TITLE
Upgrade to XCode 9 causes Swift version error

### ISSUE THREAD

**Issue by bjorncooley** [urbanairship/react-native-module#129]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ iOS SDK 9.3.1

### What are the versions of any relevant development tools you are using?
ℹ This is a react native project, doing manual install of AirshipKit using the steps from the Urban Airship docs: https://docs.urbanairship.com/platform/ios/#sdk-installation

# Report

### What unexpected behavior are you seeing?
ℹ After upgrading to XCode 9, building throws the error: `The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. This setting can be set in the build settings editor.`

### What is the expected behavior?
ℹ Build successfully

### What are the steps to reproduce the unexpected behavior?
ℹ 
1. Set up react native project 
2. Download Urban Airship iOS SDK
3. Copy AirshipKit into project, add to embedded binaries, update header + frameworks search paths
4. Build using XCode 8. Everything works, yay!
5. Upgrade to XCode 9. Build explodes.

### Things we've tried
1. Update the .xcdatamodel `Code Generation` language from Swift to Objective-C
2. Set Swift language version for AirshipKit.xcodeproj to 3.3 and 4.1 in build settings

**Comment by rlepinski** [comment]
Are you using a swift module in your project? Our project does not use swift so this is a bit confusing. 

Could you share a project that reproduces this issue?

**Comment by fbartho** [comment]
@rlepinski we (I'm a colleague of @bjorncooley) are also not using Swift, which is why this was surprising.  -- Only our branch that manually integrates this module is failing in CI with this above flow.

**Comment by BrianBatchelder** [comment]
The UrbanAirship SDK has Swift in some of our sample projects, and in one unit test (AirshipKitTests). That unit test also uses a Swift library called "XcodeEdit".

I suggest you set your SWIFT_VERSION to 4.0, or stop building those targets, which you shouldn't need.

**Comment by bjorncooley** [comment]
@BrianBatchelder removing the test directory worked, thanks!
