### ISSUE TITLE
[iOS] Custom config file

### ISSUE THREAD

**Issue by vasklund** [urbanairship/react-native-module#13]
Native integration, `react-native-ua` and Android (using `AutoPilot`) allow for using a custom config file, but as far as I can tell that is not yet possible for iOS in this wrapper. This means that it's not possible to have different build targets use different settings.

**Comment by rlepinski** [comment]
@vasklund I believe you can have a different AirshipConfig.plist files included in each target. The SDK will pick up the one for the target.

How are you accomplishing this on Android?

**Comment by vasklund** [comment]
Interesting, I will give this a try on Monday! My iOS development skills are still very lacking :)

Is there any analogous way for Android? Right now I just use a custom `AutoPilot` on Android. Something like 
```
<meta-data
  android:name="com.urbanairship.autopilot"
  android:value="se.svd.start.MyAutopilot"
  tools:replace="android:value"
/>
```
in AndroidManifest.xml, then I load my config file in 
`public AirshipConfigOptions createAirshipConfigOptions(@NonNull Context context)` like this:
```
Properties properties = new Properties();
try {
  InputStream inputStream = context.getAssets().open("airshipconfig_" + BuildConfig.PRODUCT + ".properties");
  properties.load(inputStream);
} catch (IOException e) {
  throw new RuntimeException(e);
}
```
where `PRODUCT` is a config variable injected via `react-native-config`.

**Comment by vasklund** [comment]
(Right now we build the config "by hand" with
```
return new AirshipConfigOptions.Builder()
  .setDevelopmentAppKey(...)
  .setDevelopmentAppSecret(...)
```
etc., but I realized (but haven't confirmed) today that we can probably just do
```
return new AirshipConfigOptions.Builder()
  .applyProperties(context, "airshipconfig_" + BuildConfig.PRODUCT + ".properties")
  .setCustomThing("myCustomRuntimeValue");
```
instead.)

**Comment by rlepinski** [comment]
Yeah you could do that for Android instead of loading the properties file by hand. Another option is to take advantage of the "flavors" feature of Android and have a `AirshipConfig.properites` file per flavor.

**Comment by vasklund** [comment]
I've got it working now, it was indeed possible to do it simply using targets for iOS and product flavors for Android. Less code and easier to understand IMHO.

Thanks for your help!
