### ISSUE TITLE
Allow setting firebase version android in parent project

### ISSUE THREAD

**Issue by freakinruben** [urbanairship/react-native-module#137]
# Preliminary Info

Since [React-Native 0.56](https://github.com/facebook/react-native/blob/master/local-cli/templates/HelloWorld/android/build.gradle#L34) projects declare the compile version and other info in the `gradle.ext`. Similarly, react-native packages are starting to read these projects settings. An example would be [`react-native-fcm/android/build.gradle`](https://github.com/evollu/react-native-fcm/blob/master/android/build.gradle)

# Feature request

It would be great if `react-native-urbanairship` would read the project settings in a similar fashion. That would prevent any potential conflicts in firebase versions.

**Comment by rlepinski** [comment]
@freakinruben Other than fcm-core, our module does not include the FCM version by default. We could exclude the dependency from our package and reimport in this module doing what you suggest, but I am not convinced its solving any problems. Here is my reasons:

- Gradle will resolve the newest dependency already, so if package a needs 15.0 and package b needs 16.0, you will get 16.0.
- If our plugin needs the min version of 16.0 and the gradle defines 15.0, our plugin will break.
- This use to be a problem with firebase and google services, but now they are [versioned independently](https://android-developers.googleblog.com/2018/05/announcing-new-sdk-versioning.html) and you no longer need the same version for all packages.
- You can already force versions using[ resolution strategies](https://docs.gradle.org/current/dsl/org.gradle.api.artifacts.ResolutionStrategy.html)

**Comment by freakinruben** [comment]
@rlepinski Thanks for clarifying. The way you describe it, there will indeed be no conflicts (although I'm not a fan of forcing resolution strategies)

**Comment by rlepinski** [comment]
Due to issues with firebases strict version checks, we will probably do this. Someone submitted a PR already - https://github.com/urbanairship/react-native-module/pull/170
