### ISSUE TITLE
Android: Not updating the Device token

### ISSUE THREAD

**Issue by wpconsulate** [urbanairship/react-native-module#140]
I have Integrated the iOS/Android SDK's both are integrated fine. They were working a few days back but recently Android stopped registering the Push Token for device.
It is creating Channel and adding Tag for the record but isn't adding the device token.

Screenshot for Ref: http://prntscr.com/kg39yj

# Preliminary Info
I'm using 
- Node Version: v10.7.0
- npm -v6.2.0
- expo - v55.0.5

my Package.json dependencies looks like this
"dependencies": {
    "expo": "^28.0.0",
    "jsonq": "^1.1.0",
    "moment": "^2.22.2",
    "react": "16.3.1",
    "react-native": "https://github.com/expo/react-native/archive/sdk-27.0.0.tar.gz",
    "react-native-datepicker": "^1.7.2",
    "react-native-elements": "^0.19.1",
    "react-native-fabric": "0.4.1",
    "react-native-google-analytics": "^1.3.2",
    "react-native-keyboard-aware-scroll-view": "^0.5.0",
    "react-native-masked-text": "^1.7.2",
    "react-native-picker-select": "^3.1.3",
    "react-navigation": "^2.5.5",
    "urbanairship-react-native": "^1.6.2"
  }

# Report

### What unexpected behavior are you seeing?
It is not adding GCMId for Android device

### What is the expected behavior?
ℹ it should add GCM Id for device token just fine

### What are the steps to reproduce the unexpected behavior?
ℹ I don't know how we can reproduce, since It was working earlier and I haven't changed anything in Android project and react native code can't be an issue since ios device tokens are being added successfully

### Do you have logging for the issue?
Following is the log from Android Studio
- 08-08 14:04:25.984 5648-5654/com.petmeds1800.androidApp I/zygote: Do full code cache collection, code=506KB, data=364KB
- 08-08 14:04:25.987 5648-5654/com.petmeds1800.androidApp I/zygote: After code cache collection, code=493KB, data=317KB
- 08-08 14:04:28.173 5648-5654/com.petmeds1800.androidApp I/zygote: Do partial code cache collection, code=505KB, data=338KB
    After code cache collection, code=505KB, data=338KB
    Increasing code cache capacity to 2MB
- 08-08 14:04:34.051 5648-6205/com.petmeds1800.androidApp I/petmeds - UALib: Channel creation succeeded with status: 201 channel ID: f770e1b8-c0d9-48da-b877-8a1e0af614c5
- 08-08 14:04:34.121 5648-6205/com.petmeds1800.androidApp D/petmeds - UALib: RichPushUser - Updating user.
- 08-08 14:04:34.991 5648-5768/com.petmeds1800.androidApp I/petmeds - UALib: Created Rich Push user: AgUe7CshSDupTQa_Ugi3wg
- 08-08 14:04:34.996 5648-5768/com.petmeds1800.androidApp D/petmeds - UALib: RichPushUser - Setting Rich Push user: AgUe7CshSDupTQa_Ugi3wg
- 08-08 14:04:35.039 5648-5768/com.petmeds1800.androidApp I/petmeds - UALib: Refreshing inbox messages.
- 08-08 14:04:35.475 5648-5768/com.petmeds1800.androidApp I/petmeds - UALib: Received 0 inbox messages.
- 08-08 14:04:35.496 5648-5648/com.petmeds1800.androidApp E/petmeds - UALib: Unable to emit events. React Instance Manager is unavailable.
- 08-08 14:04:40.059 5648-5648/com.petmeds1800.androidApp D/petmeds - UALib: ReactAirshipReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
- 08-08 14:04:40.061 5648-5648/com.petmeds1800.androidApp E/petmeds - UALib: Unable to emit events. React Instance Manager is unavailable.
- 08-08 14:07:40.577 5648-5661/com.petmeds1800.androidApp I/zygote: Background concurrent copying GC freed 117783(4MB) AllocSpace objects, 3(60KB) LOS objects, 49% free, 5MB/11MB, paused 1.028ms total 110.516ms

**Comment by rlepinski** [comment]
Are you providing a GCM sender ID in the config ? We will need verbose logs. You can enable it by setting `developmentLogLevel` to `VERBOSE` in you airship config. 

Our 2.0 version of the module using FCM now. If you update, you are required to provide a google-services.json file. The steps are oultined in the README.

**Comment by wpconsulate** [comment]
above log was already from setting `developmentLogLevel` to `VERBOSE` and about `gcmSender` that is already set in `airshipconfig.properties` file.

I can try updating the plugin

**Comment by wpconsulate** [comment]
Updating the plugin won't work since it requires me to upgrade the gradle and other play gcm services which breaks a lot of things

**Comment by rlepinski** [comment]
@wpconsulate The logs you are posting show the log level being set to DEBUG, if we had verbose we would see the payloads the Channel Registration is sending to verify where the issue is.

**Comment by wpconsulate** [comment]
@rlepinski those are logs from Verbose let me post updated log with screenshots

**Comment by rlepinski** [comment]
@wpconsulate `Airship log level: 3`, 3 = VERBOSE.

**Comment by wpconsulate** [comment]
@rlepinski Please check this Verbose Logs http://prntscr.com/kh5749
Find logs under this gist
https://gist.github.com/wpconsulate/b4f3e42c19344fb84b54939a2356c3a9

**Comment by wpconsulate** [comment]
@rlepinski I have added the `developmentLogLevel = VERBOSE` un airshipconfig.properties file and updated the log here https://gist.github.com/wpconsulate/b4f3e42c19344fb84b54939a2356c3a9

Please let me know if that helps?

**Comment by wpconsulate** [comment]
@rlepinski I firgured out that no matter what I send in `UrbanAirship.setUserNotificationsEnabled(true);` -> `true` or `false` the SDK always make call to UA server with `"opt_in":false,`

here are the logs from the app when we toggle Push Notifications

> 08-13 13:58:24.458 17266-17467/com.petmeds1800.androidApp I/ReactNativeJS: Opt Status:
> 08-13 13:58:24.461 17266-17467/com.petmeds1800.androidApp I/ReactNativeJS: true
> 08-13 13:58:24.469 17266-17351/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PreferenceDataStore - Saving preference: com.urbanairship.push.USER_NOTIFICATIONS_ENABLED value: true
> 08-13 13:58:24.496 17266-17266/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Received intent: Intent { act=RUN_JOB cmp=com.petmeds1800.androidApp/com.urbanairship.job.AirshipService (has extras) }
> 08-13 13:58:24.497 17266-18924/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Running job: JobInfo{action=ACTION_UPDATE_CHANNEL_REGISTRATION, id=5, extras='{}', airshipComponentName='com.urbanairship.push.PushManager', isNetworkAccessRequired=true, initialDelay=0, persistent=false}
> 08-13 13:58:24.498 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Performing channel registration.
> 08-13 13:58:24.500 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Should update registration. Channel registration payload has changed.
> 08-13 13:58:24.501 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: ChannelApiClient - Updating channel with payload: {"identity_hints":{"user_id":"oXGZJ703QOGfmbbIIzGpSA"},"channel":{"background":false,"timezone":"Asia\/Kolkata","set_tags":true,"device_type":"android","opt_in":false,"locale_language":"en","locale_country":"GB","tags":["GARYK54"]}}
> 08-13 13:58:24.527 17266-17266/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Received intent: Intent { act=RUN_JOB cmp=com.petmeds1800.androidApp/com.urbanairship.job.AirshipService (has extras) }
> 08-13 13:58:24.530 17266-18924/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Running job: JobInfo{action=ACTION_UPDATE_CHANNEL_REGISTRATION, id=5, extras='{}', airshipComponentName='com.urbanairship.push.PushManager', isNetworkAccessRequired=true, initialDelay=0, persistent=false}
> 08-13 13:58:26.754 17266-17484/com.petmeds1800.androidApp I/PetMeds4Vets - UALib: Channel registration succeeded with status: 200
> 08-13 13:58:26.756 17266-17351/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PreferenceDataStore - Saving preference: com.urbanairship.push.LAST_REGISTRATION_PAYLOAD value: {"identity_hints":{"user_id":"oXGZJ703QOGfmbbIIzGpSA"},"channel":{"background":false,"timezone":"Asia\/Kolkata","set_tags":true,"device_type":"android","opt_in":false,"locale_language":"en","locale_country":"GB","tags":["GARYK54"]}}
> 08-13 13:58:26.764 17266-17266/com.petmeds1800.androidApp D/PetMeds4Vets - UALib: ReactAirshipReceiver - Received intent with action: com.urbanairship.push.CHANNEL_UPDATED
> 08-13 13:58:26.779 17266-17351/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PreferenceDataStore - Saving preference: com.urbanairship.push.LAST_REGISTRATION_TIME value: 1534148906755
> 08-13 13:58:26.795 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: Job - Finished: JobInfo{action=ACTION_UPDATE_CHANNEL_REGISTRATION, id=5, extras='{}', airshipComponentName='com.urbanairship.push.PushManager', isNetworkAccessRequired=true, initialDelay=0, persistent=false} with result: 0
> 08-13 13:58:26.796 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Performing channel registration.
> 08-13 13:58:26.796 17266-18924/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Component finished job with startId: 1
> 08-13 13:58:26.797 17266-17484/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Channel already up to date.
>     Job - Finished: JobInfo{action=ACTION_UPDATE_CHANNEL_REGISTRATION, id=5, extras='{}', airshipComponentName='com.urbanairship.push.PushManager', isNetworkAccessRequired=true, initialDelay=0, persistent=false} with result: 0
> 08-13 13:58:26.797 17266-18924/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: AirshipService - Component finished job with startId: 2

So something wrong in UA SDK (Android) here because RN code looks good and works fine ( for iOS )

**Comment by rlepinski** [comment]
@wpconsulate I do not think its an issue with the UA SDK but rather something interfering with Google's GCM registration. Your channel is opted out because it does not contain a registration token.

This line is not returning the token - https://github.com/urbanairship/android-library/blob/9.0.6/urbanairship-sdk/src/main/java/com/urbanairship/push/gcm/GcmPushProvider.java#L47. Could you provide the output of `./gradlew app:dependencies`. You said it use to work, do you remember what changed when it stopped?

**Comment by wpconsulate** [comment]
@rlepinski below is the output of `./gradlew app:dependencies`
https://gist.github.com/wpconsulate/b9a8586dd7883fdde3f26e8de1ba685d

Also nothing really have been changed earlier I just updated the he Long Server key from Firebase http://prntscr.com/ki4ajp into UA Api Key http://prntscr.com/ki4b09

nothing else was done on UA SDK setup

**Comment by rlepinski** [comment]
@wpconsulate could you try disabling expo's `GcmRegistrationIntentService` ? I wonder if its a race condition in the GCM packages

**Comment by wpconsulate** [comment]
okay I can try that give me sometime

**Comment by wpconsulate** [comment]
yes disabled using

```
<service
      android:name=".gcm.GcmRegistrationIntentService"
        android:enabled="false"
      android:exported="false">
    </service>
```

**Comment by wpconsulate** [comment]
Nope still not working https://gist.github.com/wpconsulate/32168993232e30e90de80ba7b952e233

**Comment by rlepinski** [comment]
@wpconsulate Well, I guess thats a good thing because if that was the issue it would be been difficult to work around.

I think I need a project to reproduce the issue. Are you comfortable sharing something with me? I could provide my email so you can avoid sharing it public.

**Comment by wpconsulate** [comment]
@rlepinski  yeah sounds good, Project is hosted with github I can provide you access to the Project if you need?

**Comment by wpconsulate** [comment]
@rlepinski Also I noticed that, even after inital App load if I try to toggle notifications it doesn't make any update on UA account. I guess that is because log shows

> 08-13 22:33:59.541 16111-16378/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Performing channel registration.
> 08-13 22:33:59.543 16111-16378/com.petmeds1800.androidApp V/PetMeds4Vets - UALib: PushManagerJobHandler - Channel already up to date.

**Comment by rlepinski** [comment]
@wpconsulate `rlepinski` is my gh user.

The CRA behavior is all working as expected. The GCM registration piece is broken for whatever reason.

**Comment by wpconsulate** [comment]
provided you access on the repo

**Comment by wpconsulate** [comment]
let me know if I can help in quick setup? but I guess you are the expert :)

**Comment by Canedo** [comment]
Hello guys!

Is there any news on this issue? We are facing a "similar issue" here on our application but we are having problems trying to reproduce it on a reliable way, so any extra input for this particular issue may be applicable to our apps.

Hope you guys can find out any positive outcome.

**Comment by wpconsulate** [comment]
@Canedo please share your `app/build.gradle` file in order to be sure of the similar issue

**Comment by wpconsulate** [comment]
@rlepinski Thanks you are life saver :)

**Comment by rlepinski** [comment]
It was due to an out of date version of GPS. 

@Canedo I do not want this to become a catch all for everyone. Please open a new issue explaining how your issue is similar.
