### ISSUE TITLE
iOS: setUserNotificationsEnabled doesn't wait on users response

### ISSUE THREAD

**Issue by freakinruben** [urbanairship/react-native-module#141]
# Preliminary Info

### What Urban Airship dependencies are you using?
`"urbanairship-react-native": "2.0.0",`

# Report

### What unexpected behaviour are you seeing?
When I call `UrbanAirship.setUserNotificationsEnabled(true)` I would expect the function to return a promise that resolves when the user rejects or accepts the permission request. Instead, the function doesn't wait, making it difficult to act upon the response of a user.

### What is the expected behavior?
I would expect it to behave in the same way as [PushNotificationIOS.requestPermissions](https://react-native.org/doc/pushnotificationios.html#requestpermissions). Return a promise that either resolves to `true` or `false`, depending on wether the user gave permission.

### What are the steps to reproduce the unexpected behavior?
Install a fresh iOS app and request notification permissions using the urbanairship react-native-module.
I know, there is a work around which requires adding a listener for `notificationOptInStatus`. But this requires quite a lot of code when you try to use it from redux-saga. Returning a promise would make this integration a lot easier.

**Comment by rlepinski** [comment]
That would be neat. Its not going to be easily accomplished without SDK changes. I will talk to my team about it.

**Comment by rlepinski** [comment]
@freakinruben We will be able to do this once we release our iOS SDK 10.0 that targets iOS 10+. The registration flow for iOS 9 that our SDK 9 supports make this difficult to accomplish. SDK 10.0 should be out around the time iOS 12 is released.

**Comment by freakinruben** [comment]
Thanks for the update @rlepinski , that's great to hear!

**Comment by MaxInMoon** [comment]
Resolved with v2.1.0?
