### ISSUE TITLE
Change inProduction value depending which Environment app is using

### ISSUE THREAD

**Issue by Diego-Franco** [urbanairship/react-native-module#142]
is a way to change the inProduction variable on fly? 

i know for android we have `airshipconfig.properties` file, or we can have the `AutoPilot` class, but in this case in the react native module, the AutoPilot is on the Android folder of the library.

is possible to use my own `AutoPilot` file in my Android folder and reuse the same code from the library?

**Comment by rlepinski** [comment]
You could use manifest overrides to remove our entry and use your entry. However if you do not specify `inProduction` in your airshipconfig, we will try to detect it based on the environment. Here is how we do it - https://github.com/urbanairship/android-library/blob/master/urbanairship-core/src/main/java/com/urbanairship/AirshipConfigOptions.java#L945

Basically we look for the debug flag in the BuildConfig. Should work for majority of apps.

**Comment by Diego-Franco** [comment]
Thank you for the response, I made the changes with the first option:

I have my build configuration like:
debug
test/ semi-prod
prod

so the problem was with the `test/ semi-prod` because, the build is like `test build` so was not easy to change the inProduction value.

but i extended my class from your` Autopilot` class and replace in my `Manifest` and now I'm able to use for both in the same build

**Comment by otusweb** [comment]
@rlepinski I have an app for which the default detection did not work. What can I do to figure out what breaks that detection (i'm not an android dev, mainly iOS...)
Or could you point to how I can provide two different AirshipConfig.properties file?
