### ISSUE TITLE
Problems with Android Opt-out users

### ISSUE THREAD

**Issue by Canedo** [urbanairship/react-native-module#143]
# Preliminary Info

this is part of our package.json dependencies:
```
{
    "react": "16.4.1",
    "react-native": "0.55.4",
    "react-native-animatable": "1.3.0",
    "react-native-cache": "1.1.1",
    "react-native-code-push": "5.3.5",
    "react-native-device-info": "0.21.5",
    "react-native-draftjs-render": "2.8.2",
    "react-native-fabric": "0.5.1",
    "react-native-fast-image": "4.0.14",
    "react-native-firebase": "4.3.7",
    "react-native-image-gallery": "2.1.5",
    "react-native-in-app-browser": "3.1.0",
    "react-native-iphone-x-helper": "1.0.3",
    "react-native-linear-gradient": "2.4.0",
    "react-native-open-settings": "1.0.1",
    "react-native-orientation": "3.1.3",
    "react-native-userdefaults-ios": "0.1.3",
    "react-navigation": "2.11.2",
    "urbanairship-react-native": "1.6.2"
}
```

Urban Airship dependencies:
```
        implementation "com.google.android.gms:play-services-gcm:12.0.1"
        implementation "com.google.firebase:firebase-appindexing:12.0.1"
        implementation 'com.urbanairship.android:urbanairship-sdk:9.0.2'
        implementation 'com.facebook.react:react-native:+'
```
# Report

### What unexpected behavior are you seeing?
Our Android RN apps (iOS are fine) are setting users to opt-out on background and we can't find what is really happening. When the user reopen the app, it changes the status to opt-in.

### What is the expected behavior?
Not opting-out the user unless the user really set it manually on app configuration.

### What are the steps to reproduce the unexpected behavior? Do you have logging for the issue?
We are trying for days to reproduce the opt-in to opt-out scenario and capture logs to help solving this issue but we don't have any logs at the moment.

**Comment by rlepinski** [comment]
Is it a specific device set? Do these users have a registration token? What percentage of your audience? Can you give me any more info?

**Comment by Canedo** [comment]
51,6% are opt-out at the moment. We couldn't identify a device pattern, mainly because it's happening a lot.

We don't use / handle the registration token but i can provide you my / some teammates registrations token if needed. Everybody here that use Android have face this 'opt-out issue'.

**Comment by rlepinski** [comment]
Do you have a device currently that is opted-out ? Could you capture verbose logs on that device?

**Comment by Canedo** [comment]
Unfortunately we don't have. We are keeping some devices logging but we are failing to get the moment where a device become opted-out. We are trying but it's tricky. Any update on logs I will send to you.

We handle ```setUserNotificationsEnabled``` when the user open the app and the userNotification is not enabled.

Something like that:

```
UrbanAirship.isUserNotificationsEnabled().then((enabled: Boolean) => {
  if (!enabled) {
    UrbanAirship.setUserNotificationsEnabled(true);
  }
});
```

**Comment by rlepinski** [comment]
@Canedo, so you only set it to true? Could you provide the output of `./gradlew app:dependencies` ?

**Comment by Canedo** [comment]
@rlepinski Can i send this on private?

**Comment by rlepinski** [comment]
@Canedo Sure, how do you want to do that? my email is ryan.lepinski@urbanairship.com

**Comment by Canedo** [comment]
Works perfectly for me.
