### ISSUE TITLE
Authorized Notification Settings not found on object type 'UAPush'

### ISSUE THREAD

**Issue by jongirard** [urbanairship/react-native-module#144]
# Preliminary Info

### What Urban Airship dependencies are you using?
- UrbanAirship-iOS-SDK (9.0.2)
- urbanairship-react-native@2.0.1

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

- react-native 0.5.6

### What unexpected behavior are you seeing?

Xcode build is failing with error `Property 'authorizedNotificationSettings' not found on object of type 'UAPush *'; did you mean 'authorizedNotificationOptions'?`

### What is the expected behavior?
 - Build should succeed to enable Urban Airship functionality

### What are the steps to reproduce the unexpected behavior?
 
- react-native install urbanairship-react-native
- react-native link urbanairship-react-native
- Pod added to podfile (pod 'UrbanAirship-iOS-SDK', '~>9.0')
- pod install
- added config to plist

### Do you have logging for the issue?

No

**Comment by rlepinski** [comment]
You need to have `UrbanAirship-iOS-SDK` 9.3 or newer.
