### ISSUE TITLE
[iOS] Add Cocoapods podspec 

### ISSUE THREAD

**Issue by AntiHate** [urbanairship/react-native-module#149]
We're linking every RN library via cocoapods, this one missing podspec file. Currently we don't use npm link for iOS.

This is what we've in 'urbanairship-react-native.podspec'

```
require "json"

package = JSON.parse(File.read(File.join(__dir__, "package.json")))

Pod::Spec.new do |s|
  s.name         = "urbanairship-react-native"
  s.version      = package["version"]
  s.summary      = package['description']
  s.author       = package['author'] 
  s.homepage     = package['homepage']
  s.license      = package['license']
  s.platform     = :ios, "8.0"
  s.source       = { :git => "https://github.com/urbanairship/react-native-module.git", :tag => "v#{s.version}" }
  s.source_files  = "ios/**/*.{h,m}"
  s.dependency "React"
  s.dependency "UrbanAirship-iOS-SDK"
end
```

and in our podfile

`  pod 'urbanairship-react-native', :path => '../node_modules/urbanairship-react-native'`

Should this be added in the next release?
Thanks!

**Comment by rlepinski** [comment]
How are you pulling in our JS files? Does that get installed through npm?

**Comment by AntiHate** [comment]
We do everything as stated in the installation guide, even run the npm link command but manually discard 'npm link' changes in iOS directory and then use podspec file. Not sure if we can run npm link just for android.

**Comment by AntiHate** [comment]
```
react-native install urbanairship-react-native
react-native link urbanairship-react-native
```

After running the above commands, we discard the iOS changes and then add the podspec file.

iOS successfully builds and we use `import { UrbanAirship } from 'urbanairship-react-native';` in JS.

**Comment by rlepinski** [comment]
@AntiHate Thanks for the suggestion. We are going to take a look to see how we can incorporate this into a future release.

**Comment by AntiHate** [comment]
Thanks! @rlepinski

**Comment by 1e1f** [comment]
+1, CocoaPods instead of XCode Project dependencies is my preferred method as well -- I would also add (a little nit) that the naming convention for RN modules would expect "react-native-urbanairship" instead of "urbanairship-react-native". I think I saw reference to 3 different names in the README, so if the name is still up in the air I would go with the "norm".

**Comment by driley-emoney** [comment]
We'd benefit from this too. We are currently creating our own podspec for your lib and placing it in our project. Seems like a simple fix, just add a podspec to the repo.

**Comment by rlepinski** [comment]
We will get to this soon. I did not realize that react-native link supported cocoapods, so this should make our integration easier.

**Comment by rlepinski** [comment]
Added in 3.1.0. Working on a 4.0.0 release with React Native .60 support
