### ISSUE TITLE
Event "Register" only triggered when the app is on background

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-module#154]
We've recently upgraded to UA SDK 9, before this we are using the SDK 8+ until recently.

I've implemented `addListener` for the `register` event. Somehow, even after the user have given the permission it is not triggering any event. But if I moved out of the app and put it on the background I can see the event being triggered.

This is not the case when we're at SDK 8 though. We needed the channel ID right when after the user give the consent it so we rely on the `register` event since `getChannelId` will always return `null` on the first time.

"react-native": "version": "0.55.4"
"urbanairship-react-native":  "version": "2.0.2"

**Comment by crow** [comment]
@idrakimuhamad thanks for bringing this to our attention. This should be fixed in the next release. Relevant bug is fixed here: https://github.com/urbanairship/react-native-module/pull/153
