### ISSUE TITLE
Need Way to Know the Time of a Deep Link Notification Is Fired

### ISSUE THREAD

**Issue by ruangchupa** [urbanairship/react-native-module#156]
# Preliminary Info

### What Urban Airship dependencies are you using?
"urbanairship-react-native": "1.6.2"

### What are the versions of any relevant development tools you are using?
"react-native": "0.55.4"

# Report

### What unexpected behavior are you seeing?
I can't find any way to know the date/time of a deep link notification is fired.

### What is the expected behavior?
A way to get date/time of when a particular deep link notification is fired.

**Comment by rlepinski** [comment]
Could you explain why you need this? Assuming you add a deep link listener on app init they should be fired within a few ms from when you receive the event.

**Comment by ruangchupa** [comment]
@ralepinski Thanks for responding. My objective is that I want to do an action only when a user tap a deep link notification that received within a minute before.

**Comment by rlepinski** [comment]
@ruangchupa We have no way of tracking the post date on iOS, so you would have to send the time with extras.

**Comment by ruangchupa** [comment]
I see. Thanks @rlepinski for responding.
