### ISSUE TITLE
Registration token:  undefined

### ISSUE THREAD

**Issue by MartinSandstrom** [urbanairship/react-native-module#158]
# Preliminary Info

### What Urban Airship dependencies are you using?
Urbanairship-react-native 1.6.2

### What unexpected behavior are you seeing?
When 'register' event are triggered, registration token is undefined.
Registration token:  undefined

When calling getRegistrationToken(), registration token in undefined.

### What is the expected behavior?
I cannot find any information about this in the docs, but i assume the registration token should be returned?

```js
constructor(props) {
    super(props);
    UrbanAirship.setUserNotificationsEnabled(true);
        
    UrbanAirship.addListener("register", (event) => {
      console.log('Event', event);
      
      UrbanAirship.getRegistrationToken().then(registrationToken => {
        console.log('TOKEN', registrationToken); // registrationToken is undefined
      })
      console.log('Channel registration updated: ', event.channelId);
      console.log('Registration token: ', event.registrationToken); // registrationToken is undefined
    });
  }
```

**Comment by rlepinski** [comment]
What platform? Are you running this in a simulator?

**Comment by MartinSandstrom** [comment]
Yes i am running this in the Version 10.0 (SimulatorApp-851.2 CoreSimulator-518.22)

**Comment by rlepinski** [comment]
On iOS, the simulator does not support device token registration. You have to use a real device.

**Comment by MartinSandstrom** [comment]
Can we add this to the documentation? Its a bit confusing when some values are returned but not others.

**Comment by rlepinski** [comment]
@MartinSandstrom https://github.com/urbanairship/react-native-module/pull/160
