### ISSUE TITLE
Getting Error: No visible @interface for 'UARCTMessageViewController' declares the selector 'loadMessage:onlyIfChanged:'

### ISSUE THREAD

**Issue by alihamza** [urbanairship/react-native-module#161]
# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ urbanairship-react-native: 2.0.3 and UrbanAirship-iOS-SDK 10.0.1

### What are the versions of any relevant development tools you are using?
ℹ 
XCode: 10.0
react-native: 0.55.2
node v8.11.2
npm 6.4.1 

# Report

### What unexpected behavior are you seeing?
ℹ After adding Urban Airship library, I am getting following error:
No visible @interface for 'UARCTMessageViewController' declares the selector 'loadMessage:onlyIfChanged:'

### What are the steps to reproduce the unexpected behavior?
ℹ Follow the instructions to add React Native UrbanAirship

**Comment by rlepinski** [comment]
You need to use either the 2.1.1 version of the plugin or downgrade the UA iOS SDK to 9.x to continue using 2.0.3.
