### ISSUE TITLE
Production app receiving development push

### ISSUE THREAD

**Issue by otusweb** [urbanairship/react-native-module#162]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info
I have tested the app in development and have now switched to production.
On the phone that I use for testing, I installed the production version of the app, launched it, but I'm not receiving the production notifications. Instead I receive the development push notifications.
I double check my build process and it updates the airshipconfig.properties file and set inProduction to true.

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.

    "urbanairship-react-native": {
      "version": "2.0.3",
      "resolved": "https://registry.npmjs.org/urbanairship-react-native/-/urbanairship-react-native-2.0.3.tgz",
      "integrity": "sha512-2L5Zou50PjwJiXy1nzbNlj6JwBmSMVtD9yNaMcfPmco9e+RIVDP5x5+3DDkjiodz2ViRavhSbkeDmxYj2Mimkw=="
    },

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
Production build receives development notifications

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
Production build receive production notifications

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.

I'm also interested in how I can debug this.

**Comment by rlepinski** [comment]
Can you set `productionLogLevel = INFO` and look for the log output of this line:
```
        Logger.info("UA Version: " + getVersion() + " / App key = " + options.getAppKey() + " Production = " + options.inProduction);
```
Make sure its your production app key and secret. If it is, most likely your production app is not configured with the correct FCM credentials in the dashboard. For help with that please contact our support team.

You are receiving your dev app pushes still because its an active channel configured with the same FCM token. To stop receiving pushes from the dev app, you could switch FCM config, force a new token, or opt out of your dev channel. However its probably not worth doing any of those things as this is only an issue when you are developing the app.

**Comment by otusweb** [comment]
ok thanks for the clarification. Other who have the app installed don't have this issue. So i'll just leave with the fact that it is my phone.

It would be great if the UA framework could detect the change from production to development and force to refresh the token.

**Comment by BrianBatchelder** [comment]
Thanks for your feedback, @otusweb. We'll look into your suggestion.
