### ISSUE TITLE
ARC Semantic Issue Xcode 10 Build

### ISSUE THREAD

**Issue by jongirard** [urbanairship/react-native-module#163]
# Preliminary Info

### What Urban Airship dependencies are you using?
` "urbanairship-react-native": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/urbanairship-react-native/-/urbanairship-react-native-2.1.1.tgz"`

### What are the versions of any relevant development tools you are using?
- Xcode 10
- iOS 12.0.0
- React Native 0.5.6

# Report

### What unexpected behavior are you seeing?
During Xcode build and run on device, Error is produced of type "ARC Semantic Issue" with report: `/Users/username/JS/app/node_modules/urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m:71:22: No visible @interface for 'UAPush' declares the selector 'enableUserPushNotifications:'`

### What is the expected behavior?
Previous build in the same environment using urbanairship-react-native v2.0.1 and iOS11 did not produce any errors and registered to the push notification service correctly.

### What are the steps to reproduce the unexpected behavior?
Update package to latest version (2.1.1). Clean project, remove node_modules (rm -rf node_modules) and run `npm install`.  Attempt to build and run on device.

### Do you have logging for the issue?
No further logs were produced.

**Comment by rlepinski** [comment]
Please update your UA iOS SDK to 10+.
