### ISSUE TITLE
Crash when opening notification on android 8.0.0

### ISSUE THREAD

**Issue by otusweb** [urbanairship/react-native-module#165]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
"urbanairship-react-native": {
      "version": "2.1.1",
      "resolved": "https://registry.npmjs.org/urbanairship-react-native/-/urbanairship-react-native-2.1.1.tgz",
      "integrity": "sha512-exwJEKdt4sd2JWdwlfjI8jhS/Mt93h3EoFz6cdL6/AunhTfo+eugF9UjfjnvfivsaDPEtz8Sb3m8LZ/+Pa14ZA=="
    },

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
I got an android user report a crash after opening a push notification and the app is stuck. Could not be restarted without uninstalling app first.

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
App does not crash after click on push notification and app relaunch correctly.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.
Device: SM-G930F (R16NW)
Android: 8.0.0

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.

Stack trace:
Attempt to invoke virtual method 'com.urbanairship.json.JsonMap com.urbanairship.json.JsonValue.optMap()' on a null object reference
com.urbanairship.push.TagGroupsMutation in fromJsonValue at line 287
com.urbanairship.iam.tags.TagGroupHistorian$MutationRecord in fromJsonValue at line 197
com.urbanairship.iam.tags.TagGroupHistorian$MutationRecord in fromJsonList at line 219
com.urbanairship.iam.tags.TagGroupHistorian in getMutationRecords at line 140
com.urbanairship.iam.tags.TagGroupHistorian in recordMutation at line 109
com.urbanairship.iam.tags.TagGroupHistorian in access$000 at line 31
com.urbanairship.iam.tags.TagGroupHistorian$1 in onMutationUploaded at line 61
com.urbanairship.push.TagGroupRegistrar in notifyListeners at line 192
com.urbanairship.push.TagGroupRegistrar in uploadMutations at line 159
com.urbanairship.push.NamedUserJobHandler in onUpdateTagGroup at line 169
com.urbanairship.push.NamedUserJobHandler in performJob at line 78
com.urbanairship.push.NamedUser in onPerformJob at line 97
com.urbanairship.job.Job$1 in run at line 91
java.util.concurrent.ThreadPoolExecutor in runWorker at line 1162
java.util.concurrent.ThreadPoolExecutor$Worker in run at line 636
java.lang.Thread in run at line 764

**Comment by rlepinski** [comment]
Thanks for the report. I am looking into this now. This will require a change to https://github.com/urbanairship/android-library and then an update to the module to use the new SDK.  It may take a day or so to release.

**Comment by rlepinski** [comment]
@otusweb I am having a difficult time figuring out how the users app got into that state. Could you provide SDK/react plugin versions you have used in the past?

**Comment by rlepinski** [comment]
@otusweb Ok, I found the issue. We have a race condition that will insert an unexpected null into our storage if a named user ID changes in the middle of a named user tag group update. This should be extremely rare but unfortunately it completely breaks the app if its wedged into that state.

Getting a release out that should fix that race condition and handle any null values in the store.

**Comment by rlepinski** [comment]
Fixed in 2.1.3

**Comment by otusweb** [comment]
Thanks for the quick turnaround. i'll integrate this in my next release
