### ISSUE TITLE
notification for logged in user still received after logout

### ISSUE THREAD

**Issue by otusweb** [urbanairship/react-native-module#174]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
 "urbanairship-react-native": "2.2.0"

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.
React native 0.57.8

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
Once a user is logged in the app, I call:
```
    UrbanAirship.setAnalyticsEnabled(true);
    UrbanAirship.setUserNotificationsEnabled(true);
    UrbanAirship.setNamedUser(user.username);
```

During the user sign out I call:
```
    UrbanAirship.setNamedUser(null);
    UrbanAirship.setAnalyticsEnabled(false);
    UrbanAirship.setUserNotificationsEnabled(false);
```

If another user signs in on the same device, then the next notification that is received the deepLink event is fired twice.
If the app is restarted, it seems like the deeplink event is fired only once

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
I expect to receive the notification only once

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.
add a listener for deeplink event
`UrbanAirship.addListener("deepLink",...`
Run the application call the sign in code above, sign out code above, then sign in again with a different named user.
Send a notification

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.

**Comment by crow** [comment]
Hey @otusweb, thanks for reporting this. Looking into it now.

**Comment by crow** [comment]
@otusweb When and where are you making the call to add the listener for the deep link event? Code samples would be ideal.

**Comment by otusweb** [comment]
Thanks for your question. I think I know what the issue is.
The addListener call is made after signin. So in the case where a user signs in, then out then in, the addListenener event has been called twice.
So I'm assuming the callback is then called twice.

I guess the solution would be for me to remove the deep-link listener when the user signs out.

Could you add some info around this in the doc ("don't forget to remove the listener" or "make sure you call this only once")

**Comment by crow** [comment]
@otusweb Yeah this is something we can definitely make more clear in the readme. Thanks for this insight.
