### ISSUE TITLE
Custom Interactive Notification

### ISSUE THREAD

**Issue by idrakimuhamad** [urbanairship/react-native-module#176]
I need to use the custom interactive notification (https://docs.urbanairship.com/platform/ios/push-notifications/#interactive-notifications). But the guide is in the native's integration. 

Do we have this available in the React Native module? Because I couldn't find it in anywhere in the docs? (http://docs.urbanairship.com/reference/libraries/react-native/latest/index.html)

**Comment by rlepinski** [comment]
The plugin does not currently support custom interactive notifications. The plugin installs the native SDK so you can access that directly and create custom categories.

**Comment by idrakimuhamad** [comment]
i thought so, and got the same reply from support.

> The plugin installs the native SDK so you can access that directly and create custom categories.

When you said this, you meant to do so ourselves by creating our own bridge/module to create the category? Unfortunately we don't have expertise in the native land. We will opt out from this feature for now. Hopefully it can be made available in the future.

Thanks @rlepinski

**Comment by rlepinski** [comment]
@idrakimuhamad We added support for custom categories in 3.0.0. You have to define the categories in a plist file for iOS, and an xml file for Android. Its documented here - https://docs.airship.com/platform/react-native/push-notifications/#adding-custom-notification-categories

**Comment by idrakimuhamad** [comment]
Thats great stuff. Thanks guys.
