### ISSUE TITLE
Pending Notifications in notification bar all gone when I kill the app

### ISSUE THREAD

**Issue by johnnycc8** [urbanairship/react-native-module#177]
# Please fill out this template when submitting an issue.
All lines beginning with an ℹ symbol indicate information that's important for you to provide to ensure your issue is resolved as quickly and efficiently as possible.

❗For how-to inquiries involving Urban Airship functionality or use cases, please
contact (support)[https://support.urbanairship.com/hc/en-us].

# Preliminary Info

### What Urban Airship dependencies are you using?
ℹ Please include Urban Airship dependencies and their versions here.
Testing on Android
"urbanairship-react-native": "2.0.3"

### What are the versions of any relevant development tools you are using?
ℹ If applicable, please include any relevant information about the version of your
IDE, plugin(s), or package manager(s) here.
Visual Studio Code 1.33.0

# Report

### What unexpected behavior are you seeing?
ℹ Please provide a brief description of the unexpected behavior here.
Pending Notifications in notification bar are all gone when I kill the app.

### What is the expected behavior?
ℹ Please provide a brief description of the expected behavior here.
Pending Notifications should remains there even if I kill the app, as long as I didn't unregister.

### What are the steps to reproduce the unexpected behavior?
ℹ Please provide reproduction steps here.
send a few testing urbranairship notifications, then try to kill the background app.

### Do you have logging for the issue?
ℹ Please provide links to gists of any pertinent logs here.
N/A.

Is there any known issue for this thank you?

**Comment by rlepinski** [comment]
How are you killing the app? If you force stop the app Android removes all of the notifications for that app. There is nothing the app can do to prevent that. If you want a change to that behavior please file a bug on Android.

**Comment by johnnycc8** [comment]
Hi @rlepinski, 
I am trying to remove the app from running in background. However I don't think this is android OS related, as if you try the same for "Whatsapp" they could handle it well. This is why we raise the bug here instead of Android OS.

**Comment by rlepinski** [comment]
@johnnycc8 How are you killing the app and on what devices?

If i force stop whats app on my phone the notifications go away. Its a standard Android behavior.

**Comment by johnnycc8** [comment]
Hi @rlepinski , 
FYI, I am using android phone with os 4.2.2 JDQ39. I am not using the "Force stop" button to kill the app, I am just removing the app from the running app list. You can open the running app list by holding the menu button / or long press the home button, (I think there are different way to call the running app list menu per different phones), then try to swipe the running application away from the running app list, and you can see the urbanairship notification gone, but Whatsapp didn't have that issue. This is the behaviour I saw.

**Comment by rlepinski** [comment]
That is not standard behavior for Android devices. Usually when you see that behavior its either an added "battery saving" OS feature (not part of core Android), a custom rom, or a task manager app that automatically kills backgrounded apps. These apps/features usually have some sort of whitelisting capability to prevent certain apps from being affected, usually the popular messaging apps are whitelisted by default.

There is nothing an app can do to prevent this behavior from happening except instruct the end user to whitelist the app if you detect you are on one of the device/OS versions that have one of the app killing "battery saving" features.

If you need more help, please contact support.

**Comment by johnnycc8** [comment]
Hi @rlepinski ,  The strange part is that when I switch back to my original production app which used React-Native-UA on the same phone, it do not have this issue and when I kill the app, the notification still remains. That is why this issue has been raised and I thought there are ways / changes could be done to fix it. We are trying to switch to the official library as there are FCM changes.

**Comment by rlepinski** [comment]
@johnnycc8 I am unable to reproduce. Could you try seeing if you can receive a push in the background after the notifications are removed?
