### ISSUE TITLE
Android notificationOptInStatus event misses `optIn` property

### ISSUE THREAD

**Issue by vasklund** [urbanairship/react-native-module#18]
According to [the docs](https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#event:notificationOptInStatus) the `notificationOptInStatus` event should have a boolean property named `optIn`. This is true for iOS, but not for Android, where the name instead is [`optedIn`](https://github.com/urbanairship/react-native-module/blob/5347b573d54ffdf1e299408009b027819bc55e45/android/src/main/java/com/urbanairship/reactnative/events/NotificationOptInEvent.java#L18)

I assume `optIn` is the correct name? I realize it would be a breaking change to fix this, but I thought I should at least let you know :)

**Comment by rlepinski** [comment]
Will fix. Thanks for pointing this out.

Since this doesn't work as documented I think we can consider this a bug and fix it in a patch release.

**Comment by rlepinski** [comment]
Fixed in 1.1.0
