### ISSUE TITLE
getInboxMessages is always empty although the message center has lots of messages

### ISSUE THREAD

**Issue by RamyEl-basyouni** [urbanairship/react-native-module#192]
I am trying to get all messages that i have pushed to the message center but always getting empty array in both platforms android and IOS.
my code looks like:
```
UrbanAirship.setUserNotificationsEnabled(true);
UrbanAirship.getInboxMessages().then(messages => {
  alert("message inbox "+ JSON.stringify(messages))
})
```
my versions of react-native and urbanairship is as follows:
```
 "dependencies": {
    "react-native": "^0.59.8",
    "urbanairship-react-native": "^2.2.1"
  }
```
the message center dashboard is attached:
<img width="1433" alt="Screen Shot 2019-07-12 at 2 58 12 PM" src="https://user-images.githubusercontent.com/8338424/61132247-42ea4600-a4bb-11e9-9427-bdcd0def3927.png">

**Comment by BrianBatchelder** [comment]
Please contact [support](https://support.airship.com).

**Comment by RamyEl-basyouni** [comment]
This was because the account was a free account so you must subscribe to get it work.
