### ISSUE TITLE
API to enable or disable notifications

### ISSUE THREAD

**Issue by chengsam** [urbanairship/react-native-module#195]
# Preliminary Info

### What Airship dependencies are you using?
urbanairship-react-native@3.1.1

### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?
There is a switch in my app for user to enable or disable receiving push notifications without going to the Settings app. But I can't find a way to enable or disable programmatically to receive push notifications or not. I've tried `setUserNotificationsEnabled` to `false` but I can still receive push notifications. (Both Android and iOS)

### What is the expected behavior?
Provide a method call to programmatically enable or disable push notifications. (Both Android and iOS)

### Do you have logging for the issue?

**Comment by crow** [comment]
@chengsam thanks for reporting. I'm able to verify the current API is working as expected and that pushes are not arriving on my test devices when `setUserNotificationsEnabled` is set to `false` . An important thing to keep in mind is that sometimes re-registration for push type `none` can take a moment or two to occur after `setUserNotificationsEnabled` is set to `false`. 

Have you tried reproducing your issue on the provided sample application? This might be helpful in isolating the strange behavior you've seen.
