### ISSUE TITLE
displayMessage throws error if optional argument is not given

### ISSUE THREAD

**Issue by pflenker** [urbanairship/react-native-module#196]
# Preliminary Info

### What Airship dependencies are you using?
 "urbanairship-react-native": "^3.1.1"
### What are the versions of any relevant development tools you are using?
Xcode 10.3
# Report

### What unexpected behavior are you seeing?
App crashes if optional parameters are not passed.
Call `UrbanAirship.displayMessage(messageId)` on iOS, the app crashes.

### What is the expected behavior?
The same as `UrbanAirship.displayMessage(messageId, false)`, as `false` is the default value for the second argument as per the documentation. 

### What are the steps to reproduce the unexpected behavior?
Call `UrbanAirship.displayMessage(messageId)` with a valid messageId.

### Do you have logging for the issue?
```
Argument 1 (BOOL) of UrbanAirshipReactModule.displayMessage must not be null

RCTLogArgumentError(RCTModuleMethod*, unsigned long, objc_object*, char const*)
   RCTModuleMethod.mm:67
__41-[RCTModuleMethod processMethodSignature]_block_invoke.164
-[RCTModuleMethod invokeWithBridge:module:arguments:]
facebook::react::invokeInner(RCTBridge*, RCTModuleData*, unsigned int, folly::dynamic const&)
facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)::$_0::operator()() const
invocation function for block in facebook::react::RCTNativeModule::invoke(unsigned int, folly::dynamic&&, int)
_dispatch_call_block_and_release
_dispatch_client_callout
_dispatch_main_queue_callback_4CF
<redacted>
<redacted>
CFRunLoopRunSpecific
GSEventRunModal
UIApplicationMain
main
<redacted>
```

**Comment by rlepinski** [comment]
Thanks for the report
