### ISSUE TITLE
All messages `deleted` on iOS

### ISSUE THREAD

**Issue by pflenker** [urbanairship/react-native-module#201]
# Preliminary Info

### What Airship dependencies are you using?
  "urbanairship-react-native": "^3.1.2"
### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?
On iOS, all messages returned by `UrbanAirship.getInboxMessages()` have `isDeleted` set to `true`, even messages which have not been interacted with at all. If these messages are deleted with `UrbanAirship.deleteInboxMessage()`,  they are no longer returned by `UrbanAirship.getInboxMessages()`.

### What is the expected behavior?
On Android, no messages with `isDeleted===true` are being returned by `UrbanAirship.getInboxMessages()`.
Side note: I am confused as to why there would even be a message with `isDeleted===true`returned by `UrbanAirship.getInboxMessages()`.

### What are the steps to reproduce the unexpected behavior?
Create an in app message for iOS. Load the inbox messages with `UrbanAirship.getInboxMessages()`  and log them.

**Comment by pflenker** [comment]
Side note: The app badge number on iOS matches the number of unread items, even though isDeleted is `true`.

**Comment by rlepinski** [comment]
https://github.com/urbanairship/react-native-module/blob/master/ios/UARCTModule/UrbanAirshipReactModule.m#L434

Looks like the logic is flipped. Why do we set the isDeleted on it? No idea. In native code, you can mark a message as deleted without refreshing the inbox but not through react. We will fix it but you should ignore that value as it should always be false.

**Comment by pflenker** [comment]
OK, I will ignore the value for now. Thanks!

**Comment by rlepinski** [comment]
Fixed in 3.2.0
