### ISSUE TITLE
AAPT: No resource identifier found for attribute 'appComponentFactory' in package 'android'

### ISSUE THREAD

**Issue by Zyphxion** [urbanairship/react-native-module#203]
I'm receiving this error after upgrading my version of the react-native-module.  It seems that it has something to do with the latest version requiring the compileSdkVersion being set to 28, however doing so breaks 5 other things.  So I'm wondering, is there another solution to this?  Maybe a gradle resolutionStrategy?

**Comment by rlepinski** [comment]
What other issues are you having with setting the compileSdkVersion ? What version of react?

**Comment by Zyphxion** [comment]
React Native 0.51.0
The issues that arise are 

`/private/var/root/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/7254b67b8c43bec87425db3fea0583ba/res/values-v24/values-v24.xml:3:5-157: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Borderless.Colored'.
    
/private/var/root/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/7254b67b8c43bec87425db3fea0583ba/res/values-v24/values-v24.xml:4:5-135: AAPT: Error retrieving parent for item: No resource found that matches the given name 'android:TextAppearance.Material.Widget.Button.Colored'.
    
/private/var/root/.gradle/caches/transforms-1/files-1.1/appcompat-v7-28.0.0.aar/7254b67b8c43bec87425db3fea0583ba/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.
`

That's when *only* updating the compileSdkVersion from 27 to 28.  I'm not.. exactly sure how to properly update everything else (buildToolsVersion, supportLibVersion, etc) to match, but I understand that's not really related to UA's react-native-module

I have tried a few resolution strategies, mainly this one:

`subprojects {
    project.configurations.all {
        resolutionStrategy.eachDependency { details ->
            if (details.requested.group == 'com.android.support' && !details.requested.name.contains('multidex') ) {
                details.useVersion "28.0.0"
            }
        }
    }
}`

but it has not seemed to work

**Comment by rlepinski** [comment]
Could you provide the output of `./gradlew app:dependencies` ?

**Comment by Zyphxion** [comment]
It's quite long so I hosted it here: https://pastebin.com/DMTwHhRu

**Comment by rlepinski** [comment]
You should stick with compileSdkVersion set to 28. Looks like your gradle file and dependencies are outdated. Could you provide your build.gradle files for me?


Steps you can try:
- Remove `buildToolsVersion` from your build.gradle or at the very least set it to `28.0.3`
- Use latest Google Services gradle plugin `classpath("com.google.gms:google-services:4.2.0")`
- Use latest Android gradle plugin `classpath("com.android.tools.build:gradle:3.4.0")`
- Remove GCM dependency
- Set firebaseCore version to `16.0.9`
- Set firebaseMessagingVersion version to `18.0.0`
```

**Comment by Zyphxion** [comment]
This worked for me, thank you very much for your help
