### ISSUE TITLE
[react-native][iOS] - "deepLink" event fired IOS when app is on foreground

### ISSUE THREAD

**Issue by joruro** [urbanairship/react-native-module#206]
At the moment my iOS application doesn't fire any deepLink event when the app is active/foreground.

When the app is closed, the deepLink comes in and everything works normally.

urbanairship-react-native@3.1.2

**Comment by marc-scig** [comment]
Hi @joruro, is this just a problem with iOS or do you notice a similar problem with android? Was it working for you previously, and started acting strange on the latest urbanairship-react-native plugin release?

**Comment by marc-scig** [comment]
Also: how are you sending/triggering the deep link? Code examples would be helpful.
