### ISSUE TITLE
Use without Cocoapods?

### ISSUE THREAD

**Issue by aaronbuchanan** [urbanairship/react-native-module#21]
I want to try this but we're not using cocoapods on the project because it created issues previously. I see issue #9 is looking for a carthage path, is a manual path documented anywhere?

**Comment by rlepinski** [comment]
@aaronbuchanan we will try to add carthage support sometime this week. What do you mean by a manual path? Do you want us to expose a env variable?

**Comment by aaronbuchanan** [comment]
Hi @rlepinski, sorry that wasn't more clear. By manual path, I'm asking for notes integrating without either cocoapods or carthage, via npm dependency similar to other RN libraries I've integrated (`react-native-map`'s option 3)

**Comment by rlepinski** [comment]
@aaronbuchanan Its not that straight forward to install an iOS SDK without the use of cocoapods or carthage, but if you really wanted to you can try to following https://docs.urbanairship.com/platform/ios/#manual to install the SDK into your apps project. Once that is setup you will need to adjust the header search path and possibly the library search path of the UA react module. You can find those settings in the targets build settings.

Ill see if we can figure out how to make it easier in the next release.

**Comment by rlepinski** [comment]
@aaronbuchanan We added Carthage support as well as made it easier to do a manual installation. See https://github.com/urbanairship/react-native-module#ios-installation for more details.
