### ISSUE TITLE
UAMessageView covers top of screen for a few seconds

### ISSUE THREAD

**Issue by pflenker** [urbanairship/react-native-module#212]
# Preliminary Info

### What Airship dependencies are you using?
3.2.1

# Report

### What unexpected behavior are you seeing?
When using UAMessageView, any content above the view (Navigation bar, Close button...) is covered by a white view for a few seconds/milliseconds before it appears.

### What is the expected behavior?
Everything outside of UAMessageView stays unchanged.

### What are the steps to reproduce the unexpected behavior?
Simplest test case: Create a structure like this:
```jsx
<View>
  <Text>Foo</Text>
  <UAMessageView messageId={42} />
</View>
```
The text will be covered for a bit even after the message has loaded before appearing again. In our case, a whole navigation bar is affected, including the button to dismiss the view.

**Comment by pflenker** [comment]
I am on React Native 0.59.10  and Urban Airship 3.2.1.

Here is minimal code to reproduce the issue:

```jsx
import React, { useState, useEffect } from 'react';
import {
  FlatList, TouchableOpacity, Text, View,
} from 'react-native';

import { UrbanAirship, UAMessageView } from 'urbanairship-react-native';


const UAInboxScreen = () => {
  const [items, setItems] = useState([]);
  const [messageId, setMessageId] = useState(undefined);
  async function loadItems() {
    const loadedItems = await UrbanAirship.getInboxMessages();
    setItems(loadedItems);
  }
  useEffect(() => {
    loadItems();
  }, []);
  if (messageId) {
    return (
      <View>
        <Text style={{
          color: 'red',
          fontSize: 20,
        }}
        >
          Foo
        </Text>
        <UAMessageView
          style={{
            height: 200,
          }}
          messageId={messageId}
        />
      </View>
    );
  }
  return (
    <View>
      <FlatList
        data={items}
        renderItem={({ item }) => (
          <TouchableOpacity onPress={() => {
            setMessageId(item.id);
          }}
          >
            <Text>
              {item.id}
            </Text>
          </TouchableOpacity>
        )}
        keyExtractor={item => item.id}
      />
    </View>
  );
};


export default UAInboxScreen;
```

Here is a [video](https://github.com/urbanairship/react-native-module/files/3550603/recordedVideo.zip)

**Comment by pflenker** [comment]
on iOS, the UAMessageView won't even display, with the following error : 

![image](https://user-images.githubusercontent.com/4085533/63887189-83a30d80-c9dc-11e9-8cb0-33c2eb9562d2.png)

**Comment by rlepinski** [comment]
Looks like iOS works fine on 4.x, so must be a missing file/setting on 3.x. Looking into Android next.

**Comment by rlepinski** [comment]
Ok, so iOS is broken unless you install through cocoapods. Will fix in a patch. Still trying to figure out the Android issue. The view waits until the page finishing loading before the text is visible. When I inspect the layout I can see the `Foo` text view is not blocked by the webview. Currently out of ideas why this is happening. Will continue looking into it tomorrow.

**Comment by rlepinski** [comment]
@pflenker I think I have a fix for both iOS and Android. Could you give branch `release-3.2.2` a test?

**Comment by pflenker** [comment]
I can confirm that it is now working on Android. It will take me a few days before I can test iOS though!

**Comment by pflenker** [comment]
I can also confirm that iOS works now, too. The view shows up without an error and works as expected. Looking forward to the release!

**Comment by rlepinski** [comment]
3.2.2 is out
