### ISSUE TITLE
UAMessageView displays nothing if opened from push

### ISSUE THREAD

**Issue by pflenker** [urbanairship/react-native-module#216]
# Preliminary Info

### What Airship dependencies are you using?
3.2.2

### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?
This is very similar to https://github.com/urbanairship/react-native-module/issues/200, with the following difference: Instead of calling `displayMessage` as in #200, I am trying to display `UAMessageView`. It does not show anything, unless I call `await UrbanAirship.refreshInbox();` first. I have seen this on Android.

### What is the expected behavior?
The message is loaded.

### What are the steps to reproduce the unexpected behavior?
See #200  and above.

### Do you have logging for the issue?
Unlike #200, I can see no unusual logs on React Native.

**Comment by BrianBatchelder** [comment]
Thanks for the report, @pflenker. We'll look into it.

**Comment by rlepinski** [comment]
@pflenker I am unable to reproduce. Could you provide the code that hooks up the event to showing the inbox? Are you using onLoadFinished or onLoadError callbacks?

**Comment by rlepinski** [comment]
@pflenker I see an issue where `onLoadFinished` and any web view errors in `onLoadError` will fail to emit if the message view needs to refresh the inbox first. Not sure if thats the issue you are seeing.
