### ISSUE TITLE
Could not find compatible versions for pod "UrbanAirship-React-Native-Module"

### ISSUE THREAD

**Issue by wilsolutions** [urbanairship/react-native-module#219]
# Preliminary Info
Hi, I'm trying to show a Airship prototype however I am running in the following error:
Note: I'm following this guide suggested in this repo: https://docs.airship.com/platform/react-native/getting-started/#ios-setup

### What Airship dependencies are you using?
Just the core Airship: UrbanAirship-iOS-SDK

### What are the versions of any relevant development tools you are using?
  **IDEs**:
    Android Studio: 3.5 AI-191.8026.42.35.5791312
    Xcode: 11.0/11A420a - /usr/bin/xcodebuild
  **npmPackages**:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  **npmGlobalPackages**:
    react-native-cli: 2.0.1

# Report
Not sure what to put here, sorry...Report of what =P

### What unexpected behavior are you seeing?
```
[!] CocoaPods could not find compatible versions for pod "UrbanAirship-React-Native-Module":
  In Podfile:
    UrbanAirship-React-Native-Module (from `../node_modules/urbanairship-react-native`)

Specs satisfying the `UrbanAirship-React-Native-Module (from `../node_modules/urbanairship-react-native`)` dependency were found, but they required a higher minimum deployment target.
```

### What is the expected behavior?
Everything is beautifully installed =D

### What are the steps to reproduce the unexpected behavior?
1. react-native install urbanairship-react-native react-native link urbanairship-react-native
2. cd ios
3. Then I added `pod 'UrbanAirship-iOS-SDK', '~>11.0'` to the `Podfile`
4. ios pod install
5. Error :(

### Do you have logging for the issue?
yep!
➜  ios pod install
Detected React Native module pod for UrbanAirship-React-Native-Module
Analyzing dependencies
Fetching podspec for `FBLazyVector` from `../node_modules/react-native/Libraries/FBLazyVector`
Fetching podspec for `FBReactNativeSpec` from `../node_modules/react-native/Libraries/FBReactNativeSpec`
Fetching podspec for `RCTRequired` from `../node_modules/react-native/Libraries/RCTRequired`
Fetching podspec for `RCTTypeSafety` from `../node_modules/react-native/Libraries/TypeSafety`
Fetching podspec for `React` from `../node_modules/react-native/`
Fetching podspec for `React-Core` from `../node_modules/react-native/`
Fetching podspec for `React-CoreModules` from `../node_modules/react-native/React/CoreModules`
Fetching podspec for `React-RCTActionSheet` from `../node_modules/react-native/Libraries/ActionSheetIOS`
Fetching podspec for `React-RCTAnimation` from `../node_modules/react-native/Libraries/NativeAnimation`
Fetching podspec for `React-RCTBlob` from `../node_modules/react-native/Libraries/Blob`
Fetching podspec for `React-RCTImage` from `../node_modules/react-native/Libraries/Image`
Fetching podspec for `React-RCTLinking` from `../node_modules/react-native/Libraries/LinkingIOS`
Fetching podspec for `React-RCTNetwork` from `../node_modules/react-native/Libraries/Network`
Fetching podspec for `React-RCTSettings` from `../node_modules/react-native/Libraries/Settings`
Fetching podspec for `React-RCTText` from `../node_modules/react-native/Libraries/Text`
Fetching podspec for `React-RCTVibration` from `../node_modules/react-native/Libraries/Vibration`
Fetching podspec for `React-cxxreact` from `../node_modules/react-native/ReactCommon/cxxreact`
Fetching podspec for `React-jsi` from `../node_modules/react-native/ReactCommon/jsi`
Fetching podspec for `React-jsiexecutor` from `../node_modules/react-native/ReactCommon/jsiexecutor`
Fetching podspec for `React-jsinspector` from `../node_modules/react-native/ReactCommon/jsinspector`
Fetching podspec for `ReactCommon` from `../node_modules/react-native/ReactCommon`
Fetching podspec for `UrbanAirship-React-Native-Module` from `../node_modules/urbanairship-react-native`
Fetching podspec for `Yoga` from `../node_modules/react-native/ReactCommon/yoga`
[!] CocoaPods could not find compatible versions for pod "UrbanAirship-React-Native-Module":
  In Podfile:
    UrbanAirship-React-Native-Module (from `../node_modules/urbanairship-react-native`)

Specs satisfying the `UrbanAirship-React-Native-Module (from `../node_modules/urbanairship-react-native`)` dependency were found, but they required a higher minimum deployment target.
➜  ios

**Comment by marc-scig** [comment]
Hi @wilsolutions,

I'm going to guess that the relevant detail is `Specs satisfying the `UrbanAirship-React-Native-Module (from `../node_modules/urbanairship-react-native`)` dependency were found, but they required a higher minimum deployment target.`

What is your minimum deployment target? Our iOS SDK policy is to support the last three iOS versions at the time we do a major version update. So for SDK 11 that would mean iOS 10, 11, and 12.

**Comment by wilsolutions** [comment]
Ohhhhh mannnnn
Unbelievable LOL 
Thank you, yeah, the target was wrong, it is beautifully installed now!
Pod installation complete!
👍 👍 👍

**Comment by sammahfoud** [comment]
@wilsolutions I'm sorry, it is not clear to me how did you solve the issue, can you explain ?

**Comment by marc-scig** [comment]
@sammahfoud iOS 11 is the minimum supported iOS version for the Airship SDK, and that must be reflected in your Podfile's deployment target.

**Comment by bouaoud** [comment]
hello,

someone can help me with this issue please:

 ios git:(develop) ✗ pod install
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Adding a custom script phase for Pod RNFBCrashlytics: [RNFB] Crashlytics Configuration

[!] Invalid `Podfile` file:
[!] Invalid `urbanairship-react-native.podspec` file: No such file or directory - /Users/admin/Documents/workspace.

 #  from /Users/admin/Documents/workspace X/XX/node_modules/urbanairship-react-native/urbanairship-react-native.podspec:4
 #  -------------------------------------------
 #   package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 >   sync_version = `#{__dir__}/scripts/sync_version.sh #{package["version"]}`
 #
 #  -------------------------------------------
.

 #  from /Users/admin/Documents/workspace XX/XX/ios/Podfile:17
 #  -------------------------------------------
 #    # Pods for dlp
 >    config = use_native_modules!
 #
 #  --------

the line 17 of my podfile:   config = use_native_modules!

react-native: 0.63.4
urbanairship-react-native: "^8.0.1",
cocoapods: /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods.rb
platform :ios, '11.1'
Xcode > 12

it is making me crazy, thanks for your help
