### ISSUE TITLE
Is there a way to increase or display App badge count when a PN is received?

### ISSUE THREAD

**Issue by netgfx** [urbanairship/react-native-module#225]
# Preliminary Info

### What Airship dependencies are you using?
Latest 5.0.0

# Report

### What unexpected behavior are you seeing?
Can't seem to find any information on the docs

### What is the expected behavior?
Be able to increase or change the badge count on App icon when a notification is received

**Comment by BrianBatchelder** [comment]
@netgfx : Have you tried [`setBadgeNumber(badgeNumber)`](https://docs.airship.com/reference/libraries/react-native/latest/#urbanairshipsetbadgenumber) and [`getBadgeNumber()`](https://docs.airship.com/reference/libraries/react-native/latest/#urbanairshipgetbadgenumber)?
