### ISSUE TITLE
Version 6.0.0 requires `/scripts` which is not included in the NPM package

### ISSUE THREAD

**Issue by jcleigh** [urbanairship/react-native-module#237]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
`urbanairship-react-native@6.0.0`

### What are the versions of any relevant development tools you are using?
not relevant

# Report

### What unexpected behavior are you seeing?
New code introduced in the [Podspec file](https://github.com/urbanairship/react-native-module/blob/bfd1642e9baf0872525e90a728c4f3c14f8d75f5/UrbanAirship-React-Native-Module.podspec#L4) relies on a script in the `/scripts` dir, which is [NPM ignored](https://github.com/urbanairship/react-native-module/blob/bfd1642e9baf0872525e90a728c4f3c14f8d75f5/.npmignore#L3) and so the script is not found when running from `node_modules`.

### What is the expected behavior?
The script would be present and run as intended.

### What are the steps to reproduce the unexpected behavior?
`yarn add urbanairship-react-native`
`ls`
_no `/scripts` dir found_

### Do you have logging for the issue?
no

**Comment by crow** [comment]
I'll fix this and get a patch out shortly. Thanks for reporting.

**Comment by crow** [comment]
@jcleigh @whileloup 6.0.1 is out, thanks for your patience
