### ISSUE TITLE
xCode Error expected ')'

### ISSUE THREAD

**Issue by YevheniiShabelnykkk** [urbanairship/react-native-module#239]
Hello, guys!
Can you please fix this bug with new version of library? 
<img width="880" alt="Screen Shot 2020-01-08 at 4 11 52 PM" src="https://user-images.githubusercontent.com/53472115/71984706-0dd46b80-3232-11ea-8250-eee036779bb7.png">
<img width="865" alt="Screen Shot 2020-01-08 at 4 12 32 PM" src="https://user-images.githubusercontent.com/53472115/71984713-10cf5c00-3232-11ea-8b76-7373ea95a927.png">

Or it's problem only on my mac?

**Comment by rlepinski** [comment]
What xcode version are you using? Make sure you are on Xcode 11
