### ISSUE TITLE
Adding both urbanairship-react-native RN package and UrbanAirship-iOS-SDK pod causes conflicts when building with Xcode

### ISSUE THREAD

**Issue by hkellaway** [urbanairship/react-native-module#240]
# Preliminary Info

I've followed the instructions found here for integrating Airship for a React Native application: https://docs.airship.com/platform/react-native/getting-started/

It says to add the RN package (e.g. `yarn add urbanairship-react-native`) as well as the iOS pod (i.e. `pod 'UrbanAirship-iOS-SDK', '~>12.0'`).

However, doing so causes build issues with the Xcode project. 

The `urbanairship-react-native` RN package has a dependency on pod `"Airship", "13.0.4"` which includes many of the same files as `UrbanAirship-iOS-SDK` pod in its own `Core` module. Upon building with Xcode, the duplicate files conflict. 

Uninstalling the `UrbanAirship-iOS-SDK` pod and simply using the RN package along with its `Airship` pod dependency seems to work as needed.

My question is - is it suitable to use the RN package alone? If so, the docs should be updated.

### What Airship dependencies are you using?

* `"urbanairship-react-native": "^6.0.1",` (which depends on `Airship` version `13.0.4`)
* Attempted to use `UrbanAirship-iOS-SDK` pod version `12.1.2`

### What are the versions of any relevant development tools you are using?

* Xcode version `11.2.1`

# Report

### What unexpected behavior are you seeing?

The unexpected behavior is that there are Xcode build errors. These build errors are always of the type `Lexical or Preprocessor Issue` for the `UrbanAirship-iOS-SDK` framework and indicate that one of the duplicate files is not found (e.g. `UAirship.h file not found`, `UAGlobal.h file not found`, `UAInboxUtils.h`,  etc.)

### What is the expected behavior?

The integration instructions for React Native should produce a setup free of build errors.

### What are the steps to reproduce the unexpected behavior?

Follow the React Native setup instruction including both the RN package and the `UrbanAirship-iOS-SDK` > build with Xcode

### Do you have logging for the issue?

No specific logs

Thank you!

**Comment by rlepinski** [comment]
Sorry, those docs are out of date. Adding the RN package should autolink the pod, so you should not have to modify your pod file. Please remove `UrbanAirship-iOS-SDK` from your podfile, run pod install again, and it should be fine. The README has the correct instructions. Ill work on updating the docs ASAP.

**Comment by hkellaway** [comment]
That's what I ultimately figured after a bit of time sink - updating the docs would be awesome! Thanks for the quick response
