### ISSUE TITLE
ReactMessageViewManager.java uses unchecked or unsafe operations.

### ISSUE THREAD

**Issue by wilsolutions** [urbanairship/react-native-module#250]
# Preliminary Info

### What Airship dependencies are you using?
"urbanairship-react-native": "^6.0.1".

### What are the versions of any relevant development tools you are using?
System:
    OS: macOS Mojave 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 347.05 MB / 16.00 GB
    Shell: 5.3 - /bin/zsh
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: 1.21.1 - /usr/local/bin/yarn
    npm: 6.13.4 - ~/.nvm/versions/node/v12.14.1/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
    Android SDK:
      API Levels: 23, 26, 27, 28
      Build Tools: 23.0.1, 24.0.0, 26.0.1, 26.0.2, 27.0.1, 27.0.3, 28.0.0, 28.0.1, 28.0.3
      System Images: android-26 | Google APIs Intel x86 Atom, android-29 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.5 AI-191.8026.42.35.6010548
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.12.0 => 16.12.0 
    react-native: 0.61.5 => 0.61.5

# Report

### What unexpected behavior are you seeing?
```
> Task :urbanairship-react-native:compileReleaseJavaWithJavac
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /AppDemo/node_modules/urbanairship-react-native/android/src/main/java/com/urbanairship/reactnative/ReactMessageViewManager.java uses unchecked or unsafe operations.
```

### What is the expected behavior?
Expected to build without the error message above.

### What are the steps to reproduce the unexpected behavior?
Follow the installation steps for Android then run the App one Android device.

### Do you have logging for the issue?
gradle.properties:
```
android.useAndroidX=true
android.enableJetifier=true
org.gradle.daemon=true
org.gradle.parallel=false
org.gradle.configureondemand=false
org.gradle.jvmargs=-Xmx4096M -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
```

----------------------------------------

app/build.gradle and package.json:
(https://gist.github.com/wilsolutions/40203ba06050bba39c7833e631917496)

**Comment by BrianBatchelder** [comment]
Thanks for the report. This warning should not prevent you from building, unless you have configured [lintOptions](https://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.LintOptions.html#com.android.build.gradle.internal.dsl.LintOptions:warningsAsErrors) to treat warnings as errors. We will look into addressing the warning in a future release.
