### ISSUE TITLE
Could not able to find the "urbanairship-react-native.podspec" file after upgrading to @6.1.3.

### ISSUE THREAD

**Issue by Muzzamil75** [urbanairship/react-native-module#267]
When trying to pod install it says that the podspec file not found (though the file exists in the node_modules already). Below is the unexpected behavior I am seeing.

Airship dependencies version
ℹ urbanairship-react-native": "6.1.3"

Versions of relevant development tools
 "react": "16.9",
 "react-native": "0.61.0",

Unexpected behavior 
```Invalid `Podfile` file: 
Invalid `urbanairship-react-native.podspec` file: No such file or directory```

What is the expected behavior?
It Should do pod install smoothly as before in @5.0.0

Kindly help me out ASAP.

**Comment by BrianBatchelder** [comment]
@Muzzamil75 : What steps did you take to upgrade to version "6.1.3" of our SDK?

**Comment by Muzzamil75** [comment]
had just upgraded urban-airship package from 5.0.0  to 6.1.3 and it started issue as explained above

**Comment by BrianBatchelder** [comment]
@Muzzamil75 : What version of CocoaPods are you using?

**Comment by BrianBatchelder** [comment]
@Muzzamil75 : Can you please provide us with either your Podfile, or at least the urbanairship entry in your Podfile? It will look something like this: `pod 'UrbanAirship-React-Native-Module', :path => "../node_modules/urbanairship-react-native/"`

**Comment by rlepinski** [comment]
Closing for now due to lack of response.
