### ISSUE TITLE
TypeScript definition out of date

### ISSUE THREAD

**Issue by johnfreytag-eos** [urbanairship/react-native-module#269]
# Preliminary Info

### What Airship dependencies are you using?
React Native SDK v6.1.3

# Report

TypeScript definitions for `UrbanAirship.setDataCollectionEnabled` and `UrbanAirship.setPushTokenRegistrationEnabled` are missing in the current version (see #246 ), resulting in 'Property does not exist' errors when using TypeScript.

**Comment by marc-scig** [comment]
Thanks @johnfreytag-eos,

We're working on an SDK update to the plugin right now, so I'll add a ticket to fix this and there should be a new version published in the next few days.

**Comment by jcleigh** [comment]
`UrbanAirship.setAutobadgeEnabled` is also missing.

**Comment by marc-scig** [comment]
@jcleigh Yep, we noticed a bunch of things that were missing in there. Update will be out soon.

**Comment by BrianBatchelder** [comment]
Version 7.0.0 of the Airship React-Native plugin is now available. Please update and let us know if you see further issues.
