### ISSUE TITLE
v8.0.0 - iOS & Android missing from the NPM package

### ISSUE THREAD

**Issue by jcleigh** [urbanairship/react-native-module#287]
# Preliminary Info

### What Airship dependencies are you using?
`urbanairship-react-native@8.0.0`

### What are the versions of any relevant development tools you are using?
- `yarn@1.21.1`
- `xcode@11.5`

# Report

### What unexpected behavior are you seeing?
The NPM package is missing most of the necessary files. v8.0.0 only contains:
```
js           
lib          
node_modules 
package.json
```
Pods will not install because:
`[!] No podspec found for urbanairship-react-native in ../node_modules/urbanairship-react-native`

### What is the expected behavior?
NPM package should contain `ios` and `android` directories. 
Pods should install successfully.

For example, v7.0.0 contains:
```
android                           
js                                
package.json                      
urbanairship-react-native.podspec
ios                               
node_modules                      
scripts
```

### What are the steps to reproduce the unexpected behavior?
```
yarn add urbanairship-react-native@8.0.0
cd node_modules/urbanairship-react-native
ls
```
and/or
```
yarn add urbanairship-react-native@8.0.0
cd ios && pod install
```

### Do you have logging for the issue?
n/a

**Comment by crow** [comment]
@jcleigh Thanks for reporting, looking into it.

**Comment by crow** [comment]
@jcleigh found the issue, will get a fix out soon.

**Comment by pawangiri** [comment]
It's also missing `common-build.gradle` file, and path needs correction (if we want to keep the file in root).

`apply from: "../../common-build.gradle"` -> `apply from: "../common-build.gradle"`

**Comment by gauthamilango** [comment]
@crow How long do you think it will take to fix this issue? If it's gonna take time, which version should we be using?

**Comment by crow** [comment]
A patch will be out either before the end of this week or early next week. Previous versions are fine to use - 7.0.0 is the last version released. Module version 7.0.0 uses iOS SDK 13.3.2 and Android SDK 13.1.2. Thanks for your patience.

**Comment by gauthamilango** [comment]
@crow Thank you!

**Comment by crow** [comment]
@gauthamilango @pawangiri Version 8.0.1 is released, let us know if you run into any other issues
