### ISSUE TITLE
[IOS & Android ] Can't change inbox messages of "message center" dynamically 

### ISSUE THREAD

**Issue by MohamedAbdElmoniem** [urbanairship/react-native-module#291]
- latest version 8.0.1

- i can't change inbox of message center dynamically between users.
so if i logged in to my app and tried to switch to another user the same inbox for the first user remains !

- i expect when i change the. user. and namedUser of the message center dynamically i should see the inbox updated with the current logged in user not the first one.

- try to change namedUser dynamically and the device will keep the first inbox for the first logged in user.

**Comment by BrianBatchelder** [comment]
@MohamedAbdElmoniem : Are you still experiencing this problem?

**Comment by MohamedAbdElmoniem** [comment]
yes still facing this issue :(

**Comment by BrianBatchelder** [comment]
Thank you. I will take a look at it today.

**Comment by MohamedAbdElmoniem** [comment]
okay many thanks to you :).

**Comment by BrianBatchelder** [comment]
@MohamedAbdElmoniem : Are you seeing this on iOS, Android, or both?

**Comment by BrianBatchelder** [comment]
@MohamedAbdElmoniem : Message center users and [named users](https://docs.airship.com/platform/react-native/segmentation/#named-users) are different concepts. The message center user is tied to the channel id, so changing the named user has no effect. 

You could filter the listing by the named user, if you added the named user as an extra to each of the message center messages. For further help with that, I suggest contacting [Airship Support](https://support.airship.com).

I have also sent a request to the product manager to consider adding a feature that would meet your needs.
