### ISSUE TITLE
TypeScript: `extras` type

### ISSUE THREAD

**Issue by davidgovea** [urbanairship/react-native-module#301]
# Preliminary Info

### What Airship dependencies are you using?

`"urbanairship-react-native": "^9.0.0"`
### What are the versions of any relevant development tools you are using?

VSCode, TypeScript 3.x and 4.x
# Report

### What unexpected behavior are you seeing?
Hi UA team,
I noticed an inconsistency with the types for `extras`:

I believe the type for [`InboxMessage['extras']`](https://github.com/urbanairship/react-native-module/blob/main/urbanairship-react-native/js/UrbanAirship.ts#L106) is incorrect. It is currently `Map<string, string>`, meaning that TypeScript expects [Map's](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map) `.get`, `.set`, etc methods to be present.

This property is backed by `WriteableMap` on Android and `NSDictionary` on iOS, which both correspond to plain JS objects when serialized across the react-native bridge.

A type of `Record<string, string>` would be more appropriate, or the [custom JSONObject](https://github.com/urbanairship/react-native-module/blob/main/urbanairship-react-native/js/Json.ts) type could be used, as it is for [`PushReceivedEvent['extras']`](https://github.com/urbanairship/react-native-module/blob/main/urbanairship-react-native/js/UrbanAirship.ts#L128)

---

Not a big issue. Thanks for your efforts on RN! The process of keeping up-to-date and adopting the recent multi-package approach for location has been very smooth.

**Comment by marc-scig** [comment]
Hey @davidgovea,

Thanks for the feedback! We're still getting the hang of TS so this is helpful info. Glad to hear that integration has been going smoothly for you, and I'll make sure we get a ticket on the board to address this in an upcoming release.

**Comment by rlepinski** [comment]
Fixed in 10.0.0. Thanks!
