### ISSUE TITLE
Could not able to find the "urbanairship-react-native.podspec" file after upgrading to @9.0.1

### ISSUE THREAD

**Issue by Muzzamil75** [urbanairship/react-native-module#302]
When trying to pod install it says that the podspec file not found (though the file exists in the node_modules already). Below is the unexpected behavior I am seeing.

Airship dependencies version
ℹ urbanairship-react-native": "6.1.3"

Versions of relevant development tools
"react": "16.9",
"react-native": "0.61.0",

Unexpected behavior
Invalid `Podfile` file: Invalid `urbanairship-react-native.podspec` file: No such file or directory

What is the expected behavior?
It Should do pod install smoothly as before in @5.0.0

Kindly help me out ASAP.

**Comment by marc-scig** [comment]
Hi @Muzzamil75,

What does your Podfile look like? We changed the plugin in 6.1.1 to use a monorepo structure, so it's possible your app is looking for the podspec in the wrong path.
