### ISSUE TITLE
Disabling quietTime also disables userNotifications

### ISSUE THREAD

**Issue by dlindstrm** [urbanairship/react-native-module#31]
Hi,

I'm experiencing problem when using `setUserNotificationsEnabled()` and `setQuietTimeEnabled()`. Both these functions seems to be connected in some way; `isUserNotificationsEnabled()` and `isQuietTimeEnabled()` always returns the same value...
For example, when I run `setQuietTimeEnabled(false)`, the userNotifications also gets disabled (and also the other way around).

Is this expected?

Release 1.2.0 together with RN 0.47.

**Comment by rlepinski** [comment]
Fixed in with #38 . We will get a release out today.

**Comment by rlepinski** [comment]
Fixe in 1.2.1
