### ISSUE TITLE
IOS - Module 'AirshipKit' not found

### ISSUE THREAD

**Issue by ChetanaJavali** [urbanairship/react-native-module#311]
# Preliminary Info

### What Airship dependencies are you using?
 UrbanAirship-iOS-SDK (~> 10.0.3)

### What are the versions of any relevant development tools you are using?
 Xcode (Version 12.3 (12C33)) 
Node - v14.15.1
npm - 6.14.8

# Report

### What unexpected behavior are you seeing?

Pod install throws - [!] Unable to find a specification for `UrbanAirship-iOS-SDK (~> 10.0.3)`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

**Ran pod install --repo-update**  --->
CocoaPods was not able to update the `cocoapods` repo. If this is an unexpected issue and persists you can inspect it running `pod repo update --verbose`

**Ran pod repo update --verbose** as mentioned - 
It gives :

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:178:in `rescue in update_git_repo'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:169:in `update_git_repo'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source.rb:347:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in `block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in `block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in `block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `open'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in `update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Then used the command - npm start
It showed - Expo DevTools is running at http://localhost:19005

**Opened the Xcode and open the file - insights.xcodeproj**
 **It is throwing the error - Module 'AirshipKit' not found**

<img width="694" alt="Screen Shot 2021-01-25 at 1 37 42 PM" src="https://user-images.githubusercontent.com/24590697/105770135-a5772b80-5f13-11eb-84b6-552b47dac4f5.png">

### What is the expected behavior?
Expecting for the build tp be successful and be able to run the app locally

### What are the steps to reproduce the unexpected behavior?
Tried multiple solutions :

1. - reinstalled the pods
2. pods folder deletion
3. pod clean
4. pod deintegrate
5. setting up project from beginning

Nothing worked so far

Can anybody please help in resolving this issue. !!

### Do you have logging for the issue?
https://github.com/CocoaPods/CocoaPods/issues/10201

**Comment by marc-scig** [comment]
Hi @ChetanaJavali,

If `pod repo update` is failing, that's not something we have any control over. Version 10.0.3 is published and can be installed, as per my own testing. It looks like there may be information missing the stack trace you shared. You may also want to look through old CocoaPods issues to see if there are any with similar looking errors. For example: https://github.com/CocoaPods/CocoaPods/issues/6190

**Comment by ChetanaJavali** [comment]
@marc-scig After I ran pod repo update --verbose, I did not see error whereas in Xcode, i see missing AirshipKit 
Does it mean the repo did not update

**Comment by marc-scig** [comment]
@ChetanaJavali Your original question showed that the `pod repo update` step failed. If it's still saying `CocoaPods was not able to update the cocoapods repo` and giving you a stacktrace, then something probably needs to be fixed with your Cocoapods environment. Otherwise if that step is working, then you should be able to run pod install, which should succeed without any errors about not being able to find the specification. Those are prerequisites to being able to link again AirshipKit in Xcode.

**Comment by ChetanaJavali** [comment]
@marc-scig After running the  pod repo update verbose it states - /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:178:in rescue in update_git_repo' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:169:in update_git_repo'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source.rb:347:in update' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:135:in block (3 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in section' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:134:in block (2 levels) in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in each' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:133:in block in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in open' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:131:in update'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/repo/update.rb:23:in run' /Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in run' /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in <top (required)>'
/usr/local/bin/pod:23:in load' /usr/local/bin/pod:23:in

I guess the repo got updated 

Later if  run the pod install again after this , i Get - Unable to find a specification for UrbanAirship-iOS-SDK (~> 10.0.3)

**Comment by rlepinski** [comment]
@ChetanaJavali Are you still having issues? `UrbanAirship-iOS-SDK` is our old pod spec. You should use a modern version of the module and it has a podspec provided with it.
