### ISSUE TITLE
In-App Messaging - React Native

### ISSUE THREAD

**Issue by colaquecez** [urbanairship/react-native-module#318]
Hi,  is In-App Messaging implemented on react native? in the doc i did not found any information about listeners, and my version is 11 but there is not the methods. anyone can help me?

**Comment by rlepinski** [comment]
Yes IAA is available. What are you looking for in terms of listeners? What are your use cases?

**Comment by colaquecez** [comment]
> Yes IAA is available. What are you looking for in terms of listeners? What are your use cases?

In the doc i did not find any information about how implement it on javascript, only how use in native projects (swift,kotlin)  :(
do you have any information about how implement that?

**Comment by rlepinski** [comment]
There is really no integration needed to use the feature. Through the dashboard, you can customize the look, feel, content, and when a message displays. The SDK will display the IAA on top of your react native app.

**Comment by colaquecez** [comment]
Hmmm, i need call a function on javascript when the IAA opens in my screen, but in the doc does not have information about how do that,   
for exemple, Push notification there is a tutorial about how implement the listerners on javascript.

**Comment by rlepinski** [comment]
@colaquecez What method do you need to call when an IAA is being displayed?

**Comment by colaquecez** [comment]
@rlepinski I need call the method `messageWillBeDisplayed` on react native, it exists on javascript or i will need create my own bridge?

**Comment by rlepinski** [comment]
@colaquecez I just want to make sure it works the way you are expecting. IAA will display the messages without any work on your part. What are you planning on doing in messageWillBeDisplayed?

**Comment by colaquecez** [comment]
for example, when the `messageWillBeDisplayed ` is showed i wanna push an information on firebase, do you have any example with the implementation on react native using the feature IAA?

**Comment by rlepinski** [comment]
@colaquecez why did you close it? Sorry, I had some other commitments that took priority over this.

If we were to expose the listeners to react, i would prefer not to expose the entire message as its complicated json. What info are you thinking you would need from the message?

**Comment by colaquecez** [comment]
Hey @rlepinski, it`s works,  thank you man fo helping :) :)
