### ISSUE TITLE
Rich push notification on IOS

### ISSUE THREAD

**Issue by colaquecez** [urbanairship/react-native-module#324]
Hey, im trying to show an image in my push notification but it doesn't work, in the doc i don't found any information about how implement it, anyone that uses react native got implement rich notification airship?

**Comment by rlepinski** [comment]
You have to add the [notification service extension ](https://docs.airship.com/platform/ios/getting-started/#notification-service-extension)

It can be tricky to setup. Please contact support if you still have issues.

**Comment by colaquecez** [comment]
Yeah but we using react native, in the section doesn't have information about that, I will need get in touch with support? :/

**Comment by rlepinski** [comment]
React native does not have support for plugins to add an extension. You will have to implement it directly in the Xcdoe project following the instructions linked. The sample app in the repo has it implemented as well.
