### ISSUE TITLE
Example APP are crashing on Android

### ISSUE THREAD

**Issue by igorhernandezdev** [urbanairship/react-native-module#331]
Hey guys, i cloned react-native-module and installed all dependencies but are crashing here, i don't know why, i tried too change for another branch but anyway are crashing, someone else have this issue? thanks for now!

**Comment by rlepinski** [comment]
Without logs we are not able to help. You dont see anything in your consoles? What about logcat?

My guess is you did not create a valid `airshipconfig.properties` file in the android project.

**Comment by igorhernandezdev** [comment]
Thanks Brow, i found what is happend! thanks anyway for support, good week to us.
