### ISSUE TITLE
Calling UrbanAirship.displayMessageCenter() does nothing

### ISSUE THREAD

**Issue by inturbidus** [urbanairship/react-native-module#335]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

 "dependencies": {
    "@dynatrace/react-native-plugin": "^2.214.1",
    "@hookform/resolvers": "^2.4.0",
    "@react-native-clipboard/clipboard": "^1.8.2",
    "@react-native-community/art": "^1.2.0",
    "@react-native-community/async-storage": "^1.9.0",
    "@react-native-community/checkbox": "^0.5.8",
    "@react-native-community/cookies": "git+https://github.com/Loxrie/cookies.git#f4324eccf54dc4fe35689811531340b5d0fa4411",
    "@react-native-community/datetimepicker": "^3.4.3",
    "@react-native-community/geolocation": "^2.0.2",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-native-firebase/app": "^12.0.0",
    "@react-native-firebase/crashlytics": "^12.0.0",
    "@react-native-firebase/database": "^12.0.0",
    "@react-native-picker/picker": "^1.9.3",
    "@react-navigation/bottom-tabs": "^5.11.11",
    "@react-navigation/material-top-tabs": "^5.3.15",
    "@react-navigation/native": "^5.9.4",
    "@react-navigation/stack": "^5.14.5",
    "@reduxjs/toolkit": "^1.5.0",
    "@timwangdev/react-native-geocoder": "^1.0.0-alpha.6",
    "babel-loader": "^8.0.6",
    "card-validator": "^8.0.0",
    "date-fns": "^2.8.1",
    "form-data": "^3.0.0",
    "format-json": "1.0.3",
    "i18next": "^19.4.5",
    "identity-obj-proxy": "3.0.0",
    "jetifier": "^1.6.6",
    "js-base64": "^3.4.5",
    "json5": "^2.2.0",
    "morphism": "^1.12.3",
    "patch-package": "^6.4.7",
    "postinstall-postinstall": "^2.1.0",
    "prop-types": "15.7.2",
    "query-string": "^6.13.1",
    "ramda": "^0.26.1",
    "react": "16.13.1",
    "react-fast-compare": "^3.2.0",
    "react-hook-form": "^7.3.4",
    "react-i18next": "^11.5.0",
    "react-is": "^17.0.2",
    "react-native": "0.63.2",
    "react-native-animatable": "1.3.3",
    "react-native-barcode-builder": "^2.0.0",
    "react-native-bootsplash": "^3.2.3",
    "react-native-branch": "^5.0.2",
    "react-native-config": "0.12.0",
    "react-native-default-preference": "^1.4.3",
    "react-native-device-info": "^8.1.3",
    "react-native-dialog": "5.6.0",
    "react-native-fast-image": "^8.3.4",
    "react-native-fbsdk-next": "^4.3.0",
    "react-native-gesture-handler": "^1.10.3",
    "react-native-i18n": "git+https://github.com/AlexanderZaytsev/react-native-i18n.git#3d600e9",
    "react-native-image-zoom-viewer": "^3.0.1",
    "react-native-keyboard-aware-scroll-view": "^0.9.3",
    "react-native-keychain": "^6.0.0",
    "react-native-localize": "^1.4.0",
    "react-native-maps": "react-native-community/react-native-maps",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal": "^11.5.3",
    "react-native-modal-datetime-picker": "^9.2.0",
    "react-native-modal-selector": "^1.1.5",
    "react-native-orientation-locker": "^1.3.1",
    "react-native-permissions": "^3.0.1",
    "react-native-picker-select": "^8.0.4",
    "react-native-raw-bottom-sheet": "^2.2.0",
    "react-native-reanimated": "^1.13.3",
    "react-native-render-html": "5.1.0",
    "react-native-restart": "^0.0.22",
    "react-native-root-toast": "3.2.1",
    "react-native-safe-area-context": "^3.2.0",
    "react-native-screens": "^3.2.0",
    "react-native-search-bar": "^3.5.1",
    "react-native-snackbar": "^2.2.0",
    "react-native-snap-carousel": "^4.0.0-beta.6",
    "react-native-svg": "^12.1.0",
    "react-native-tab-view": "^2.14.4",
    "react-native-text-input-mask": "^2.0.0",
    "react-native-url-polyfill": "^1.3.0",
    "react-native-vector-icons": "6.6.0",
    "react-native-webview": "11.2.3",
    "react-redux": "^7.2.1",
    "reactotron-react-native": "^5.0.0",
    "redux-persist": "^6.0.0",
    "redux-saga": "1.0.5",
    "rn-range-slider": "^1.3.2",
    "route-parser": "^0.0.5",
    "scandit-react-native-datacapture-barcode": "^6.7.3",
    "scandit-react-native-datacapture-core": "^6.7.3",
    "urbanairship-react-native": "11.0.1",
    "url": "^0.11.0",
    "yup": "^0.32.9"
  },
  "devDependencies": {
    "@babel/core": "7.9.6",
    "@babel/runtime": "7.9.6",
    "@react-native-community/eslint-config": "^2.0.0",
    "@types/jest": "^25.2.3",
    "@types/node": "^13.11.1",
    "@types/ramda": "^0.27.7",
    "@types/react-is": "^17.0.1",
    "@types/react-native": "^0.63.2",
    "@types/react-native-dialog": "^5.6.1",
    "@types/react-native-snap-carousel": "^3.8.2",
    "@types/react-native-text-input-mask": "^0.7.4",
    "@types/react-native-vector-icons": "^6.4.5",
    "@types/react-redux": "^7.1.5",
    "@types/react-test-renderer": "^16.9.2",
    "@types/seamless-immutable": "^7.1.11",
    "@typescript-eslint/eslint-plugin": "^2.27.0",
    "@typescript-eslint/parser": "^2.27.0",
    "babel-jest": "^24.9.0",
    "babel-plugin-module-resolver": "^4.1.0",
    "eslint": "^7.23.0",
    "eslint-config-prettier": "^6.10.0",
    "eslint-config-standard": "^14.1.0",
    "eslint-plugin-import": "^2.20.1",
    "eslint-plugin-node": "^11.0.0",
    "eslint-plugin-promise": "^4.2.1",
    "eslint-plugin-standard": "^4.0.1",
    "jest": "^25.1.0",
    "metro-react-native-babel-preset": "^0.59.0",
    "prettier": "^2.2.1",
    "react-native-svg-transformer": "^0.14.3",
    "react-test-renderer": "16.9.0",
    "typescript": "^3.8.3",
    "yarn-run-all": "^3.1.1"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
### What are the versions of any relevant development tools you are using?

# Report

### What unexpected behavior are you seeing?

          UrbanAirship.displayMessageCenter() does nothing.  No logs, no nothing. 

### What is the expected behavior?

Message center should show.

### What are the steps to reproduce the unexpected behavior?

Call UrbanAirship.displayMessageCenter()
### Do you have logging for the issue?

It is the weirdest thing, I have checked to ensure the call is made.  All other Airship functions are working.  It almost seems like the navigation stack is preventing it from being shown.
<img width="1122" alt="Screen Shot 2021-07-09 at 10 46 26 PM" src="https://user-images.githubusercontent.com/905441/125149534-91ad3380-e107-11eb-97ca-e56ba2fc493a.png">

**Comment by rlepinski** [comment]
Thanks for the report, I think I see the issue. Looks like an issue only on iOS or are you also seeing this on Android? On IOS it assumes the app is setup to display an a message center in react-native, so calling `displayMessageCenter` will cause a message center event to fire. Ill get a ticket on our board to make the OOTB message center work again.

**Comment by oristanovic** [comment]
@inturbidus are you calling  `UrbanAirship.setAutoLaunchDefaultMessageCenter` before `displayMessageCenter` ? If it's  being set to false or was set to false before, the message center won't display. Also, are you seeing this on both iOS and Android?
