### ISSUE TITLE
Feature Request: Mixpanel RTDS Integration

### ISSUE THREAD

**Issue by jacquesdev** [urbanairship/react-native-module#341]
We need to do this integration within our react-native project
https://docs.airship.com/partners/mixpanel/#mixpanel-rtds-integration, however, it looks like no react-native implementation for this exists.

Could this get added?

**Comment by rlepinski** [comment]
We have a way to set associated identifiers - https://docs.airship.com/reference/libraries/react-native/latest/urbanairship-react-native/classes/_urbanairship_.urbanairship.html#associateidentifier

Do you have access to the mix panel ID?

**Comment by gatlinhebert** [comment]
Hey @jacquesdev, we've added an example to the docs here: https://docs.airship.com/partners/mixpanel/#react-native-rtds-setup

If you have any trouble implementing the integration I recommend creating a [support ticket](https://support.airship.com/) so our Partner team can help.

**Comment by jacquesdev** [comment]
Thank you! Much appreciated, will take a look

**Comment by jacquesdev** [comment]
Going to close this issue, much appreciated :)
