### ISSUE TITLE
dismissMessageCenter() will not close opened message center

### ISSUE THREAD

**Issue by ananthauppangala** [urbanairship/react-native-module#342]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info
I am displaying MessageCenter using  UrbanAirship.displayMessageCenter() API, it work fine.. When I click on one of the messages, the message detail button shows with a button, which is linked to a deep link. When I  click on the button, the message center will not close even I am manually trying to dismiss through UrbanAirship.dismissMessageCenter() API on deeplink. Behind the message center my deep link works fine.. How can I dismiss the message center?

### What Airship dependencies are you using?
Latest

### What are the versions of any relevant development tools you are using?
latest

# Report

### What unexpected behavior are you seeing?
Message center will not close

### What is the expected behavior?
Message center should close  on button press from deeplink message

### Do you have logging for the issue?
No

**Comment by rlepinski** [comment]
Thanks for the report.

Are you using the OOTB message center or showing your own?
