### ISSUE TITLE
NSInvalidArgumentException - [UAPush channelID]: unrecognized selector

### ISSUE THREAD

**Issue by jacquesdev** [urbanairship/react-native-module#345]
# Preliminary Info

### What Airship dependencies are you using?
    "urbanairship-react-native": "11.0.1",

### What are the versions of any relevant development tools you are using?
SDKs:
    iOS SDK:
      Platforms: iOS 14.5, DriverKit 20.4, macOS 11.3, tvOS 14.5, watchOS 7.4
    Android SDK:
      API Levels: 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-29 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 2020.3 AI-203.7717.56.2031.7583922
    Xcode: 12.5.1/12E507 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_292 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: 5.0.1 => 5.0.1 
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 

# Report

### What unexpected behavior are you seeing?
Production app is crashing unexpectedly, whereas development is fine.

### What is the expected behavior?
That neither of them cause a crash

### What are the steps to reproduce the unexpected behavior?
This is my AirshipConfig.plist file (with real values redacted)

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>site</key>
	<string>EU</string>
	<key>developmentAppKey</key>
	<string>###############</string>
	<key>developmentAppSecret</key>
	<string>###############</string>
	<key>productionAppKey</key>
	<string>###############</string>
	<key>productionAppSecret</key>
	<string>###############</string>
	<key>URLAllowList</key>
	<array>
		<string>###############</string>
	</array>
</dict>
</plist>
```

### Do you have logging for the issue?
NSInvalidArgumentException
-[UAPush channelID]: unrecognized selector sent to instance 0x28331aee0

**Comment by rlepinski** [comment]
Do you have the stack trace? We no longer call that so I assume your plugin is not the version you think it is or something is being cached oddly.

**Comment by marc-scig** [comment]
Hi @jacquesdev,

This plugin stopped using the that call about two years ago (version 5.0). My guess is that the SDK and plugin are mismatched, and you have a newer SDK deployed with an older plugin. In theory it shouldn't even compile, so I agree with @rlepinski that's it's most likely a caching-related issue.

**Comment by jacquesdev** [comment]
Only issue is that I've never used an older version of airship before, having installed the react-native plugin version (11.01) as mentioned in the description, for the first time. 

In Podfile.lock, I can confirm I have the following:
  - urbanairship-react-native (11.0.1):
    - Airship (= 14.3.0)
    - React-Core

And I can see based on your ios-library the latest is 14.6.0, so not sure what the issue is.

In addition, I checked the podspec in the react-native bundle, can confirm this all looks correct:

```
require "json"

 package = JSON.parse(File.read(File.join(__dir__, "package.json")))
 sync_version = `#{__dir__}/scripts/sync_version.sh #{package["version"]}`

 Pod::Spec.new do |s|
  s.name         = "urbanairship-react-native"
  s.version      = package["version"]
  s.summary      = package['description']
  s.author       = package['author']
  s.homepage     = package['homepage']
  s.license      = package['license']
  s.platform     = :ios, "11.0"
  s.source       = { :git => "https://github.com/urbanairship/react-native-module.git", :tag => "{s.version}" }
  s.source_files  = "ios/**/*.{h,m}"
  s.dependency "React-Core"
  s.dependency "Airship", "14.3.0"

end
```

Any other suggestions?

**Comment by jacquesdev** [comment]
One more thing to confirm - I deintegrated my pods (and re-installed), to ensure I really have the latest iOS SDK, and it's still happening, unfortunately.

**Comment by rlepinski** [comment]
I dont think its a pod version issue, I believe you probably have an old airship react-plugin sitting around that is causing the issue. If you run it directly in xcode you should be able to figure out the exact file that is causing that issue or provide us a full stack trace.

**Comment by jacquesdev** [comment]
Ok, not sure how that is possible, my project has never had a previous version, 11.0.1 is the first version we've ever used.

Will try and get a stack trace from Xcode
