### ISSUE TITLE
13.0.0 iOS linking error. 

### ISSUE THREAD

**Issue by d-vincent** [urbanairship/react-native-module#364]
# Preliminary Info

### What are the versions of any relevant development tools you are using?

Xcode 13
# Report

### What unexpected behavior are you seeing?
The following error message when building iOS: 
`❌  ld: symbol(s) not found for architecture x86_64

❌  clang: error: linker command failed with exit code 1 (use -v to see invocation)`

### What is the expected behavior?
App builds. 

### What are the steps to reproduce the unexpected behavior?
Upgrade to 13.0.0 from 12.1.0

### Do you have logging for the issue?
Undefined symbol: os.Logger.logObject.getter : __C.OS_os_log
Undefined symbol: type metadata accessor for os.Logger
Undefined symbol: os.Logger.init(subsystem: Swift.String, category: Swift.String) -> os.Logger

I have gone back and forth between `12.1.0` and `13.0.0` multiple times. Several instances of deleting derived data, cleaning build folder, re-instaling all my pods, etc. I have not been able to avoid this error on iOS when upgrading to `13.0.0`

**Comment by AlbrechtAndrzejewski** [comment]
@d-vincent  If your project was already existing project and you tried to migrate to latest Airship version, you may find an older Swift reference laying around in your Xcode project settings.

I faced the same link problem here after migrating to Airship 16+ (intel Mac, xcode version 13.1 - 13A1030d).
Removing this value from the `LIBRARY_SEARCH_PATHS` in the _.pbxproj_ : `"\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"", ` solved this link issue on my project.

In Xcode, double click the project icon in the tree, and look for _library search paths_ in the "_Build Settings_" tab of _PROJECT_. Then click on the minus icon to remove any reference to _swift-5.0_ in the value list, be sure to keep "`$(TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)`".

**Comment by rlepinski** [comment]
@AlbrechtAndrzejewski This is super helpful, we have not been able to reproduce.
