### ISSUE TITLE
Setting the named user is not reflected in the Airship console on iOS

### ISSUE THREAD

**Issue by markwilcox** [urbanairship/react-native-module#366]
https://github.com/urbanairship/react-native-module/blob/390c0dd447dbc869cf318146d331d7e26061ad18/urbanairship-react-native/ios/UARCTModule/UrbanAirshipReactModule.m#L221

There should be a call to `updateRegistration` after the above line, as with setting other tags.

We're trying to add named user tags to our users. It's OK for new users because we can set this before the first call to enable notifications for them, which triggers an `updateRegistration` itself. The SDK doesn't expose `updateRegistration` directly either, so I'll have to hack around this by changing something which does update the registration, or existing users don't get their named user ID added.

It would be great if the above could be fixed in a future React Native SDK update so I can remove the hack from my app.

It would also be nice if the default setting of "off" for allowing named users to be set from devices in the Airship console were documented along with the front end API call.

Since it's a 1 line change I assume it's easier for you guys to do than for me to jump through the Contributor License Agreement hoop and you to verify that for a pull request.

Android appears to work fine as is.

Many thanks in advance for the time you will save future users.

**Comment by hcrowell** [comment]
Hi @markwilcox , I just updated the [docs](https://docs.airship.com/platform/react-native/segmentation/#named-users) about setting named user from devices per your suggestion:
* Added link to the named user associate API call.
* Added a screenshot to clearly specify where to allow named users to be set from devices.
