### ISSUE TITLE
Value of type 'UNNotificationSettings' has no member 'timeSensitiveSetting'

### ISSUE THREAD

**Issue by frontendwizard** [urbanairship/react-native-module#369]
I'm facing this issue reported [here](https://stackoverflow.com/questions/69525837/value-of-type-unnotificationsettings-has-no-member-timesensitivesetting-ur)

after upgrading to `v13.0.0` ios builds break with this error message:
`Value of type 'UNNotificationSettings' has no member 'timeSensitiveSetting'`
and
`Value of type 'UNNotificationSettings' has no member 'scheduledDeliverySetting'`

![](https://i.stack.imgur.com/MXXDc.png)

I'm on xCode 12.5.1.

**Comment by oristanovic** [comment]
@frontendwizard This version requires Xcode 13

**Comment by frontendwizard** [comment]
sure, I'll try that, but wouldn't it be better if the v13 where backward compatible? those lines are the only issue, if I comment them out build goes through fine. Is is possible to do a guard to check the prop availability?

**Comment by jacquesdev** [comment]
@oristanovic - can you please confirm where this requirement is documented. I've wasted hours of my life without realising this was necessary

**Comment by oristanovic** [comment]
@jacquesdev https://github.com/urbanairship/react-native-module/releases/tag/13.0.0 and https://docs.airship.com/platform/react-native/changelog/
