### ISSUE TITLE
support in-app messages

### ISSUE THREAD

**Issue by thedgbrt** [urbanairship/react-native-module#37]
The in-app messages feature doesn't seem to work. The notification is received (checked with debug: verbose) but does not display in the app.

**Comment by rlepinski** [comment]
@thedgbrt The default behavior is for the in-app to only display on the next foreground if the notification is not interacted with. Try backgrounding the app, receive the push, then open the app directly.

**Comment by thedgbrt** [comment]
@rlepinski thanks I tired it and it work! my mistake ;)
