### ISSUE TITLE
Push Notification with Deeplinks on iOS devices not working on v13.0.1 

### ISSUE THREAD

**Issue by garyjyochum** [urbanairship/react-native-module#372]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

Airship iOS SDk 16.0.2

### What are the versions of any relevant development tools you are using?

Xcode 13.1
Yarn 1.22.11
iPhone 7, iOS 15.0.2
iPhone XR, iOS 14.8 
react-native-module 13.0.1
React-native-push-notification 7.3.1

# Report

### What unexpected behavior are you seeing?

When opening a deeplink push notification on a TestFlight Staging build, the user is taken to the Home Screen.  If opening a push notification when running app in development environment (app can be completely shut down or in background mode), an exception is thrown.

### What is the expected behavior?

When a deeplink is defined for a push notification, the user is taken to that specific screen when opening it.  Deeplinks work for Android with v13.0.1.  Deeplinks for both iOS and Android worked well with react-native-module v12.0.0

### What are the steps to reproduce the unexpected behavior?

* Install app using v13.0.1 on and iOS device and receive a deeplink push notification from UA.  Open it.

### Do you have logging for the issue?

When running the app locally, the exception can be traced back to urbanairship-react-native/ios/UARCTModule/UARCTEventEmitter.m file.  In particular, the “eventBodyForNotificationContent” method when the code tries to remove the “aps” node from the response.  I have attached the screenshot as a reference.  In our React Native project, we use React Navigation and set up an object that is passed into the “linking” prop. That object is where we define listeners for the ShowInbox and DeepLink events (https://gist.github.com/garyjyochum/35e0ed74295dc216f95f079fb1728f6c).

I must also mention that our project leverages react-native-push-notification and it called in our AppDelegate when handling the didReceiveNotificationResponse event (https://gist.github.com/garyjyochum/0d2e06af6a6530ef0aefde7bf57c16ed).

 I must reiterate that this was working for both iOS and Android with urbanairship/react-native-module v12.0.0.

<img width="1672" alt="Screen Shot 2021-11-12 at 4 49 08 AM" src="https://user-images.githubusercontent.com/67169547/141799043-56e07dec-80fb-4925-84b9-63644c2b9dc7.png">

**Comment by rlepinski** [comment]
Thanks, looking into it now

**Comment by garyjyochum** [comment]
@rlepinski sure, send it on over - thank you

**Comment by rlepinski** [comment]
Its in branch `release-13.0.2`

**Comment by rlepinski** [comment]
@garyjyochum I somehow was able to get things building again and was able to both reproduce the crash and verify the fix. I will try to have a release out today

**Comment by garyjyochum** [comment]
@rlepinski i was able to confirm I am no longer seeing exceptions in that UARCTEventEmitter method and that the EventType.DeepLink event is not being handled....however, it looks like the message.deeplink in the callback is null...

<img width="851" alt="Screen Shot 2021-11-15 at 2 04 17 PM" src="https://user-images.githubusercontent.com/67169547/141839778-4785ee69-1f9c-4a81-8c90-6260552f47e7.png">

**Comment by garyjyochum** [comment]
@rlepinski An additional test for the ShowInbox event was successful.

<img width="990" alt="Screen Shot 2021-11-15 at 2 36 31 PM" src="https://user-images.githubusercontent.com/67169547/141843254-7dd8385a-bfdd-4367-a065-b1686645daed.png">
..

**Comment by rlepinski** [comment]
@garyjyochum i pushed some more changes. Deeplinks should be fixed.

**Comment by garyjyochum** [comment]
@rlepinski Confirmed - thank you so much!

**Comment by rlepinski** [comment]
Released 13.0.2
