### ISSUE TITLE
Issue adding custom notification categories

### ISSUE THREAD

**Issue by dhruvsbhatt** [urbanairship/react-native-module#374]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

`"urbanairship-react-native": "^13.0.2"`

### What are the versions of any relevant development tools you are using?

Xcode 13.1, VSCode 1.62.3
# Report

### What unexpected behavior are you seeing?

I'm not getting custom buttons in notification banner after implementing as shown here 
https://docs.airship.com/platform/react-native/push-notifications/

### What is the expected behavior?

There should be buttons displayed in notification banner on long press.

### What are the steps to reproduce the unexpected behavior?

Implement code as suggested in link
https://docs.airship.com/platform/react-native/push-notifications/
and trigger push notification

### Do you have logging for the issue?

No logs, I just receive push notifications but no buttons.

**Comment by rlepinski** [comment]
@dhruvsbhatt I was not able to reproduce, seems to be working fine for me. Did you make sure the plist is added in the copy resource phase?
