### ISSUE TITLE
displayMessage() is broken on Android

### ISSUE THREAD

**Issue by xanderdeseyn** [urbanairship/react-native-module#379]
After upgrading to 13.0.2, we can no longer open messages on Android.
We receive a native error `Invalid ID 0x00000483` and the app either hangs or does nothing.

The same code is working fine on iOS.

**Comment by rlepinski** [comment]
Thanks for the report, I dont see anything obvious. Do you have any logs other than Invalid ID 0x00000483 ?

**Comment by xanderdeseyn** [comment]
After some more digging, I found that calling `displayMessage()` triggers an infinite loop when listening to the ShowInbox event:

```UrbanAirship.addListener(EventType.ShowInbox, event => {
    if (event.messageId != null) {
      UrbanAirship.displayMessage(event.messageId)
    }
  })```

How should we handle this?

**Comment by rlepinski** [comment]
If you disable auto launch message center, then anytime the SDK gets a request to display a message it forwards that event to react native. You are then supposed to display the message within your app using our MessageView, example - https://github.com/urbanairship/react-native-module/blob/main/example/screens/MessageScreen.js

If you want to use the OOTB UI, then you should remove that listener and [enable auto launch message center](https://github.com/urbanairship/react-native-module/blob/main/urbanairship-react-native/js/UrbanAirship.ts#L916).

**Comment by xanderdeseyn** [comment]
Makes sense, thank you!
