### ISSUE TITLE
"deepLink" event not fired IOS

### ISSUE THREAD

**Issue by thedgbrt** [urbanairship/react-native-module#40]
I have an app in IOS and Android, everything works except for the "deepLink" event in IOS. When the app is closed and I open a notification with a deepLink, it doesn't trigger the event (the exact same behaviour works in Android).

Is there anything i'm missing? I did add the specific urlscheme in info.plist, and the deeplink is recognized as it does open the app when typing it in safari.

**Comment by crow** [comment]
@thedgbrt Taking a look at this. Thanks for reporting.

**Comment by rlepinski** [comment]
Fixed in 1.2.2

**Comment by fryossi** [comment]
I'm having the same issue both android and iOS (works fine when app in foreground).
"urbanairship-react-native": "1.3.1"
Podfile.lock: UrbanAirship-iOS-SDK (8.6.0).
Am i missing something?
Thanks.

**Comment by rlepinski** [comment]
@fryossi can you try to reproduce in the sample app?

**Comment by fryossi** [comment]
@rlepinski For some reason i forgot the deepLink listener...
Thanks.
