### ISSUE TITLE
Unable to trigger deeplink in iOS with string type value

### ISSUE THREAD

**Issue by andrewleeheb** [urbanairship/react-native-module#402]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
"urbanairship-hms-react-native": "^13.1.0",
"urbanairship-react-native": "^13.1.0"

### What are the versions of any relevant development tools you are using?
Visual Studio Code

# Report

### What unexpected behavior are you seeing?
The Deeplink's listener does not trigger in iOS after fire when we click on the message's button.

### What is the expected behavior?
The Deeplink's listener should trigger when button click in message.

### What are the steps to reproduce the unexpected behavior?
1. Fire a push notification from Airship console.
2. Push received and open to view.
3. Clicked on the button with Deeplink action.

### Do you have logging for the issue?
No log.

### Notes 
I've read through one of the old fixed in Cordova, https://github.com/urbanairship/urbanairship-cordova/issues/135
We've tried it seem like iOS does not recognise the value other than URL in Airship React Native.
URL it works and plain text does not work.
As expected, Android working fine with it.

**Comment by rlepinski** [comment]
Thanks we will take a look

**Comment by Ulrico972** [comment]
Hello @andrewleeheb 
I wasn't able to reproduce your case.
I tested a push with a deeplink action "fakeDeeplink" and the deeplink listener is always triggered. Same think with the deeplink on a push button.
Can you describe a bit more how do you test it please ?
Feel free also to send us some piece of code of your deeplink listener or other code that could help.

**Comment by andrewleeheb** [comment]
Hi @Ulrico972 
First I add something like this in the Airship Console
<img width="609" alt="image" src="https://user-images.githubusercontent.com/99241182/155044827-9a18f613-9c65-435f-8c71-7212c27d554e.png">
With that unusual URL template and click on the DeepLink's button, iOS doesn't trigger the deepLink event listener. 
Of course, Android is working fine.

In RN code level:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/99241182/155045001-4257901f-953e-41a1-8e95-3a0919c48604.png">
The log that we set doesn't show in the log console.

**Comment by rlepinski** [comment]
That is an invalid URI and currently wont be able to be supported by the iOS SDK. Could you change your pattern to maybe be:
`deeplink://screenname?fallback=https://www.123.com`

**Comment by andrewleeheb** [comment]
Hi @rlepinski,
Thanks for your reply.
Actually in future our App might need this button to deeplink to specific screen in the App.
That is why i put a "|" separator for that to do multi-purposes based on the business requirement.

**deeplink://screenname?fallback=https://www.123.com*
The above pattern you shared was working fine in iOS that i just tested. Is it only this way for us to do this? Cause if wanna separate this to get the value seem complicated.

**Comment by Ulrico972** [comment]
Hello,
That's not the only way. You could also use another separator, as soon as the all thing is still a valid URI.

The example that ryan sent is just a classic deep link URL, so it would be easy to get the values from the [URL object](https://developer.apple.com/documentation/foundation/url) as the scheme would be "deeplink", the host would be "screenname" and the parameters would be the key-value you put behind the "?" character.

**Comment by rlepinski** [comment]
@andrewleeheb You can format it however you want, but query params are pretty standard:
```
var url = new URL("deeplink://screenname?fallback=https://www.123.com")
url.searchParams.get("fallback")
```
To parse it out.

You might want to look into universal links as well. https://developer.apple.com/ios/universal-links/ https://developer.android.com/training/app-links

**Comment by andrewleeheb** [comment]
Hi @rlepinski  and @Ulrico972 
Tried with the above example and its working fine for both platform, Android and iOS.

Thanks for the effort.
