### ISSUE TITLE
Feature request: Message Center - Unread Count

### ISSUE THREAD

**Issue by ahmedu007** [urbanairship/react-native-module#430]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
`"urbanairship-react-native": "14.3.0"`

### What are the versions of any relevant development tools you are using?
```
System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
    Memory: 31.38 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.18.1 - ~/.nvm/versions/node/v14.18.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.18.1/bin/npm
    Watchman: 2022.03.21.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.4, iOS 15.5, macOS 12.3, tvOS 15.4, watchOS 8.5
    Android SDK: Not Found
  IDEs:
    Android Studio: 2021.2 AI-212.5712.43.2112.8512546
    Xcode: 13.4/13F17a - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.15 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.67.3 => 0.67.3 
```

Currently, there are methods within
iOS Obj-c:
```
[UAMessageCenter shared].messageList.unreadCount
```

Android Java:
```
MessageCenter.shared().getInbox().getUnreadCount()
```

To get the Unread messages count. However, there is no method within the RN API, as far as I can tell, that gives us the `unread` messages count. We want to display a new message indicator (typically a dot on top or something similar) whenever there are new messages within the Inbox.

Is there a way to do that using the current React Native APIs?

**Comment by rlepinski** [comment]
We can add that for the next release. For now you can get the list of messages and count how many are unread

**Comment by ahmedu007** [comment]
Thank you. I've opened up a PR, since that would save us from maintaining our own fork. Please let me know if there is anything I can do to escalate it. Also, how often do we get the releases? 

Thank you very much!

**Comment by ahmedu007** [comment]
Hey @rlepinski 
Thanks for merging the PR, just wanted to ask if there is a set release plan or date that we can expect this to be shipped please? 🙏
