### ISSUE TITLE
EventType.InboxUpdated is emitted once or twice p. second

### ISSUE THREAD

**Issue by gunnnnii** [urbanairship/react-native-module#436]
# Preliminary Info
We want to dispatch a request to update the MessageCenter whenever the inbox contents change. Running this callback every second is completely unnecessary and causes a lot of jank in our logs and/or devtools. Tracking these changes ourselves would add some complexity and essentially render the listener redundant.

### What Airship dependencies are you using?
`urbanairship-react-native`version `"^14.3.0"`

# Report

### What unexpected behavior are you seeing?
We see the listener callback for `InboxUpdated` event run once or twice every second, regardless of whether anything has actually changed in the inbox. I noticed this on iOS, but I've not gotten around to seeing whether this same behaviour applies to Android.

### What is the expected behavior?
The listener callback only runs when the content of the inbox has changed. (different `messageCount` or different `messageUnreadCount`).
**Bonus:** the event also provides the actual messages that were added to the inbox, so that we don't need to call `UrbanAirship.getInboxMessages` seperately.

### What are the steps to reproduce the unexpected behavior?
- Set up the `urbanairship-react-native` package.
- Add a listener for the `InboxUpdated` event
```ts
UrbanAirship.addListener(EventType.InboxUpdated, (e) => console.log(e))
```
- See that the event is fired relentlessly despite no changes in the inbox.

### Do you have logging for the issue?
We see Xcode repeatedly announce the event.
`[D] -[UAInboxMessageList updateMessages:]_block_invoke [Line 496] Inbox messages updated.`

You can also see the event runs in Javascript-land by adding a log statement into the listener callback.

**Comment by rlepinski** [comment]
Thanks for the repot, we will take a look.

**Comment by rlepinski** [comment]
@gunnnnii I am not able to reproduce, could you provide your code block? Are you calling refresh when the update happens?
