### ISSUE TITLE
iOS: Module 'AirshipKit' Not Found (Version 1.2.2)

### ISSUE THREAD

**Issue by jorgedavila25** [urbanairship/react-native-module#44]
I'm having trouble getting this RN lib (version `1.2.2`) integrated into a React Native `0.48.4` project using CocoaPods version `1.3.1` in Xcode 9.

I followed all the directions in the README and it still fails. I'm not sure how to go about setting the `AIRSHIP_SEARCH_PATH` manually, so I still can't get it to run.

I'm happy to provide more info. Thanks

![screen shot 2017-10-02 at 3 51 37 pm](https://user-images.githubusercontent.com/1642247/31096295-9fe942ba-a789-11e7-9a18-44b374f5212e.png)

**Comment by rlepinski** [comment]
@jorgedavila25, when you open the project are you using the generate .xcworkspace or .pbxproj? Could you show us all the projects within the workspace? Could you give us your Podfile as well as the output of pod update? Thanks

**Comment by jorgedavila25** [comment]
@rlepinski  Thanks for the response. So running `pod update` updated the SDK to `8.6.0` and somehow fixed this issue. Not entirely sure why though...

**Comment by rlepinski** [comment]
Yep, the plugin checks for a min version at runtime and logs a warning. We should be compatible with all 8.5+ versions

**Comment by jorgedavila25** [comment]
Gotcha. thanks for the help.

Not sure if SDK version 8.6.0 fixed the issue, or something else, but seems to be working now. Thanks!
