### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError @ PushManager.java

### ISSUE THREAD

**Issue by lukebars** [urbanairship/react-native-module#440]
# Preliminary Info

### What Airship dependencies are you using?

```
"urbanairship-react-native": "^14.3.0",
...
"react-native": "0.66.4",
```

### What are the versions of any relevant development tools you are using?

```
buildToolsVersion = "30.0.2"
minSdkVersion = 21
compileSdkVersion = 31
targetSdkVersion = 31
ndkVersion = "21.4.7075529"
```

# Report

### What unexpected behavior are you seeing?
Crash on Android devices, not depending on Manufacturer or OS version.

### Do you have logging for the issue?
```
Fatal Exception: java.lang.NoSuchMethodError
No static method d(Landroid/content/Context;)Landroidx/core/app/m; in class Landroidx/core/app/m; or its super classes (declaration of 'androidx.core.app.m' appears in /data/app/androidx.test.tools.crawler-XEAWIF3hTIRwSXh9-pIzkA==/base.apk)
keyboard_arrow_up
arrow_right
com.urbanairship.push.PushManager.<init> (PushManager.java:280)
com.urbanairship.push.PushManager.<init> (PushManager.java:258)
com.urbanairship.UAirship.init (UAirship.java:739)
com.urbanairship.UAirship.executeTakeOff (UAirship.java:420)
com.urbanairship.UAirship.access$000 (UAirship.java:66)
com.urbanairship.UAirship$2.run (UAirship.java:379)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
com.urbanairship.util.AirshipThreadFactory$1.run (AirshipThreadFactory.java:50)
java.lang.Thread.run (Thread.java:764)
```

**Comment by Apekka** [comment]
Hello, I am not able to reproduce your crash, is it happening on production or during your tests?

**Comment by lukebars** [comment]
Hey @Apekka, just a log from our production application, got it through crashlytics 👼

**Comment by lukebars** [comment]
@rlepinski only:
```
androidx.browser:browser:1.3.0
```

**Comment by rlepinski** [comment]
@lukebars How often is this crash happening? Seems to be a proguard issue, the call that it cant find is probably this:
`NotificationManagerCompat.from(context);` which is an app compat library that you should have available. If its happening with a lot of devices then its probably your pro guard settings. 

If you could provide more details on the effected devices and crash percent we might be able to help more, but again its probably proguard causing the issue.

**Comment by lukebars** [comment]
@rlepinski 
We're using a staged rollout right now, so the usage ir _really small_ - but from around 95 users, 18 were affected by this. Proguard setup wasn't really changed, except from some added lines for reanimated. Airship dependency was updated with this release, so this issue started appearing just after the update. Anything else I could provide you with? We could try adding airship proguard rules, if that would help?:
```
-keep class com.urbanairship.reactnative.** { *; }
-keep class com.urbanairship.** { *; }
```

### Devices:

> **45% Google**
> 23% sdk_goog3_x86_64
> 11% Pixel 6
> 11% Pixel 5
> 
> **22% samsung**
> 11% Galaxy S20 5G
> 11% Galaxy S9
> 
> **11%
> SHARP**
> 11% AQUOS sense2 SH-01L
> 
> **11% HMD Global**
> 11% Nokia 1


### OS:

> **23% Android 8**
> 12% Android 8.1.0
> 11% Android 8.0.0
> 
> **22% Android 9**
> 
> **22% Android 12**
> 
> **11% Android 10**
> 
> **11% Android 11**
> 
> **11% Android 13**

**Comment by rlepinski** [comment]
It's not the airship package. The missing method is in the `androidx.core` package. Could you provide your proguard config, should be in the build.gradle file. When you run that build locally it doesnt crash?

**Comment by rlepinski** [comment]
Another thing that would be helpful is the output of `./gradlew app:dependencies`

**Comment by rlepinski** [comment]
Everything looks fine, you will probably have to troubleshoot the shrinker - https://developer.android.com/studio/build/shrink-code.html#troubleshoot

This will probably fix it, but normally its not necessary.
```
-keep class androidx.core.app.** { *; }
```

Our react native module should be covered by the react-native proguard file - https://github.com/facebook/react-native/blob/f179d47fb121bfd61c6da2fbd935a8521bdb7027/ReactAndroid/proguard-rules.pro#L44.


If you are unable to reproduce on your own builds, have you tried the build that is in the app store? What is different about that machine vs your machine? I would make sure you are on the latest android build tools and gradle plugins.  I have had user report similar issues and they seem to go away with another build without any changes from them. Hopefully its something a bit more reproducible for you.

**Comment by lukebars** [comment]
Closing for now, will follow up if anything comes up
