### ISSUE TITLE
Access App Key and Secret from .env

### ISSUE THREAD

**Issue by MaganAnkur** [urbanairship/react-native-module#444]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?
13.1.1

### What are the versions of any relevant development tools you are using?
react-native - v0.67.4
react-native-config - 1.4.6

# Report

### What unexpected behavior are you seeing?
Not able to use variables from .env file in AirshipConfig.plist

### What is the expected behavior?
Dont want to expose sensitive info like APP_KEY and Secret directly in AirshipConfig.plist instead should be able to fetch from .env

**Comment by rlepinski** [comment]
You can call takeOff with all the config directly through react-native now - https://docs.airship.com/platform/react-native/getting-started/#calling-takeoff. The readme has not been updated to reflect that, but it will become the preferred and documented way of setting things up.

**Comment by MaganAnkur** [comment]
thanks @rlepinski, I got it working

**Comment by MaganAnkur** [comment]
@rlepinski I have one question, if we implement takeoff do we still need to have .plist and .properties from ios and android respectively?
Also after upgrading to v14.x.x, I noticed that getChannelId is not working anymore but with v13.1.1 it works

**Comment by rlepinski** [comment]
No, you can remove the plist and properties file. We load the config from those files if they are still available then apply any of your changes from `takeOff` call on top. 

Going to close this issue and support your channel registration issues in the other thread.
