### ISSUE TITLE
iOS authorizedStatus wrong type

### ISSUE THREAD

**Issue by diogoteix** [urbanairship/react-native-module#446]
# Preliminary Info

### What Airship dependencies are you using?
"urbanairship-react-native": "14.4.1"

### What are the versions of any relevant development tools you are using?
"react": "17.0.2",
"react-native": "0.68.2"

# Report

### What unexpected behavior are you seeing?
iOS authorizedStatus should return a string
<img width="316" alt="Screenshot 2022-08-17 at 12 21 45" src="https://user-images.githubusercontent.com/22767398/185106681-4cd476d5-0e5e-483a-9a79-aa48b09b5493.png">

### What is the expected behavior?
Typescript definition says it should return an array

### What are the steps to reproduce the unexpected behavior?
Call getNotificationStatus function in an iOS device

**Comment by rlepinski** [comment]
Fixed in 14.4.2
