### ISSUE TITLE
Android 13 - Notification permission requested on boot

### ISSUE THREAD

**Issue by JorenVos** [urbanairship/react-native-module#448]
After adding the `urbanairship-react-native` package to our project, the user has to grant permission on boot. You don't have to call any `UrbanAirship`-functionality, just installing the package is enough to encounter this issue.

# Preliminary Info

### What Airship dependencies are you using?
`urbanairship-react-native` `14.4.1`

### What are the versions of any relevant development tools you are using?
Android 13 device (Pixel 6a)

# Report

### What unexpected behavior are you seeing?
When booting an application on Android 13 that has `urbanairship-react-native` installed, users will see the native notification permission request. In our code, no interaction with any Airship-functionality is done. It should not be requested on boot without any Airship-interaction.

### What is the expected behavior?
Only check/request notification permission when calling `setUserNotificationsEnabled` for example.

### What are the steps to reproduce the unexpected behavior?
Install `urbanairship-react-native` in a React Native project.

**Comment by Ulrico972** [comment]
Hello,
I didn't manage to reproduce that behavior on our sample app. The popup is actually supposed to be shown on `setUserNotificationsEnabled` call.
Could you send us your airship config, Airship integration code, and any relevant code wherever you are using Airship code please ?
Could you also tell us on which react native version you are experiencing this issue ?

**Comment by JorenVos** [comment]
For some reason, I'm not able to reproduce the issue that I was having last week.
