### ISSUE TITLE
Android: Compatible with buildToolsVersion '23.0.1'? 

### ISSUE THREAD

**Issue by jorgedavila25** [urbanairship/react-native-module#45]
Is this plugin compatible with buildToolsVersion '23.0.1'? Seems like it requires the app to use buildToolsVersion '25.0.0`, but I'm not entirely sure. If that's the case, is there a way to make the min 23.0.1? 

I'm using version `1.2.2` of this plugin. 

Thanks

**Comment by rlepinski** [comment]
It actually needs to use 26 or newer since we now compile against 26. Any reason you are unable to update?

**Comment by jorgedavila25** [comment]
I'm not entirely sure, but wouldn't that mean that every plugin in the project would need to use 26 or above? @rlepinski

**Comment by rlepinski** [comment]
@jorgedavila25 Nope, just the consuming app. You can set it in the build.gradle file.

**Comment by rlepinski** [comment]
@jorgedavila25 The thing you want to be careful with is setting the targetSdkVersion, especially with Android O. It should be safe to set the buildToolsVersion and the compileSdkVersion.
