### ISSUE TITLE
Which documentation is the correct one?

### ISSUE THREAD

**Issue by lukebars** [urbanairship/react-native-module#457]
Hey, I've stumbled upon the docs on https://docs.airship.com/platform/react-native/getting-started/ which state completely different setup flow than indicated in this repository. 

Which is the one I should trust in?

Thanks.

**Comment by Ulrico972** [comment]
Hi,
Both are valid, they are saying pretty much the same thing, just in a different order.
I guess the easiest is to follow this doc: https://docs.airship.com/platform/react-native/getting-started/
It should be more complete if you need to go further in the features and the explanations.

**Comment by lukebars** [comment]
Hi @Ulrico972,

The documentations present with two completely different setup routes:

`docs.airship.com`:

```
 import { UrbanAirship } from 'urbanairship-react-native';

  UrbanAirship.takeOff({
    default: {
      appSecret: "REPLACE_WITH_YOUR_APP_SECRET",
      appKey: "REPLACE_WITH_YOUR_APP_KEY"
    },
    site: "us", // use "eu" for EU cloud projects
    urlAllowList: ["*"],
    android: {
      notificationConfig: {
        icon: "ic_notification",
        accentColor: "#00ff00"
      }
    }
  });
  ```
  
  
  `README.md`:
  
  ```
# Create a plist AirshipConfig.plist and include it in your application’s target:
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>developmentAppKey</key>
  <string>Your Development App Key</string>
  <key>developmentAppSecret</key>
  <string>Your Development App Secret</string>
  <key>productionAppKey</key>
  <string>Your Production App Key</string>
  <key>productionAppSecret</key>
  <string>Your Production App Secret</string>
</dict>
</plist>


# Create the airshipconfig.properties file in the application's app/src/main/assets:
developmentAppKey = Your Development App Key
developmentAppSecret = Your Development App Secret

productionAppKey = Your Production App Key
productionAppSecret = Your Production Secret

# Notification customization
notificationIcon = ic_notification
notificationAccentColor = #ff0000
```

**Comment by rlepinski** [comment]
@lukebars Both are correct, but we are going to only document calling takeOff directly from react going forward since its less error prone. We will update the repo with updated instructions in the next release. Sorry for the confusion.

**Comment by lukebars** [comment]
@rlepinski thanks, just making sure it's good for future users 😄

**Comment by isabelleaubron** [comment]
Hi, how can I set inProduction mode for iOS and Android in the React Native takeOff ? Do I need to create a airshipconfig (plist and properties) file ?
