### ISSUE TITLE
setUserNotificationsEnabled(true) Not showing dialog for Android 13 until app is relaunched (background or killed state)

### ISSUE THREAD

**Issue by KristopherHill** [urbanairship/react-native-module#470]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

"urbanairship-react-native": "14.5.1"

# Report

### What unexpected behavior are you seeing?
When calling `UrbanAirship.setUserNotificationsEnabled(true)` there is no dialog box for push notifications permissions request on Android 13 until app is relaunched (background or killed state)

### What is the expected behavior?
When `UrbanAirship.setUserNotificationsEnabled(true)` is called, push notifications permissions request dialog should appear

**Comment by rlepinski** [comment]
It will only prompt if you don't already have the permission. Verify you dont in the app settings before enabling notifications. When I install from the command line I am getting all permission granted to me becuase of this bug in 4.1.0 of AGP - https://issuetracker.google.com/issues/172112073

Might want to check that as well.

**Comment by KristopherHill** [comment]
Have checked permissions and none are enabled after install, but still not seeing the prompt

**Comment by rlepinski** [comment]
@KristopherHill Could you verify the SDK is 16.8.0. It should log a line during app start. Are you able to see notifications on that device? What about older devices?

**Comment by KristopherHill** [comment]
@rlepinski The Android SDK we're getting through is 16.8.0 - We've also found out that when we background or kill the app then open again after making the call, the prompt appears

**Comment by KristopherHill** [comment]
Turns out the issue was the targetSdkVersion being lower than 33, setting that to 33 has fixed it so worth giving that a try if you're getting the same problem
