### ISSUE TITLE
Expo Support

### ISSUE THREAD

**Issue by ShMcK** [urbanairship/react-native-module#48]
Any progress towards integrating with [Expo](https://expo.io/)?

**Comment by rlepinski** [comment]
@ShMcK I am unfamiliar with expo. What issues are you having with that framework? Could you point us to some docs on how to write an integration?

**Comment by ShMcK** [comment]
Sure.

[Expo](https://expo.io/) is a popular react-native based framework that provides an ecosystem and additional developer tools. Although they're own push notification system, it does not currently cover all use cases, such as when the app is in the background/closed and the user dismisses a notification). 

Expo has [an API for accessing native device push notifications](https://github.com/expo/expo/pull/258). Expo apps can also be detached from the system, after which other integrations can be used, such as this example with [one-signal](https://github.com/luisguilhermemsalmeida/expo-one-signal).

**Comment by andon** [comment]
This should be done by Expo. Such feature-requests are done here:
https://expo.canny.io/feature-requests
