### ISSUE TITLE
Notification Opt-In not reliable on iOS

### ISSUE THREAD

**Issue by ZdravkoN** [urbanairship/react-native-module#49]
Steps to reproduce:
- Add listener for opt-in status changes
- Add a link to settings
- Open the Settings application from the App
- Tap the back link in the header

Result: Listener is sometimes called, sometimes it isn't. 
Note: On Android, it works as expected. If I use the iOS task switcher, then it works better, but still not reliable enough.

As a workaround, I created a native module in iOS that uses **UNUserNotificationCenter** to check if the notifications are enabled when the app becomes active. This works, but I really don't want to have a separate logic for this for iOS and Android. 

Can you look into the issue?

**Comment by rlepinski** [comment]
@ZdravkoN Thanks for the report and reproduction steps. What iOS UA SDK and react-plugin are you using? Thanks

**Comment by andon** [comment]
@rlepinski 
from our `yarn.lock`
```
   urbanairship-react-native@^1.2.2:
```
from our `Podlock`
```
  pod 'UrbanAirship-iOS-SDK', '~>8.3'
```

**Comment by rlepinski** [comment]
@andon & @ZdravkoN Looks like the UA iOS SDK is not rechecking the value on app foreground. We will have a fix early next week. It should only require you to do a pod update once its out.

**Comment by rlepinski** [comment]
@andon @ZdravkoN SDK 8.6.1 is out. Please update your pod and check if your issue is resolved. Thanks!

**Comment by ZdravkoN** [comment]
@rlepinski Just tested it (sorry for the delay). Works great on iOS 9 and iOS 11. Thanks a lot 👍
