### ISSUE TITLE
Register event

### ISSUE THREAD

**Issue by gibo** [urbanairship/react-native-module#50]
I am using the npm module 1.2.2 and pod 8.5.3

```
  UrbanAirship.addListener('register', event => {
    alert('reg done!');
  });
  UrbanAirship.setUserNotificationsEnabled(true);
```

The register event never gets fired, I do however see the accept push notification alert box.

Any idea what could be wrong? This was previously working fine for me.. Is there an error event I can hook into? Or a debug mode?

**Comment by rlepinski** [comment]
@gibo the registration event only fires if something changes in the registration. If you hit no on the accept notification prompt it will not fire because the channel will still be opted out. Usually you would only use the registration event to capture the channel ID.

**Comment by rlepinski** [comment]
You probably want to use https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#event:notificationOptInStatus instead

**Comment by gibo** [comment]
ok
