### ISSUE TITLE
Message Center Title

### ISSUE THREAD

**Issue by Jahans3** [urbanairship/react-native-module#51]
Hi, first of all thanks for the awesome package.

I have a problem with the title of the message center. I read in the documentation that the message center title will default to 'Message Center' when not explicitly set, and this happens fine on iOS but on Android the title is the name of the app.

Is this a bug or are the docs out of date?
Is there a way I can set the title using this SDK or do I have to set it via native code?

Thanks

**Comment by ralepinski** [comment]
It looks like its a bug in our package - https://github.com/urbanairship/react-native-module/blob/master/android/src/main/AndroidManifest.xml#L21

We override the activity but do not set the label - https://github.com/urbanairship/android-library/blob/master/urbanairship-sdk/src/main/AndroidManifest.xml#L38

**Comment by rlepinski** [comment]
Fixed in 1.2.3
