### ISSUE TITLE
The number of unread notifications on the app icon is not reduced on iOS

### ISSUE THREAD

**Issue by dkulakov** [urbanairship/react-native-module#514]
❗For how-to inquiries involving Airship functionality or use cases, please
contact (support)[https://support.airship.com/].

# Preliminary Info

### What Airship dependencies are you using?

`"@ua/react-native-airship": "15.2.5"`

I use an auto-badge feature
`Airship.push.iOS.setAutobadgeEnabled(true);`

### What are the versions of any relevant development tools you are using?

`"react-native": "0.70.6"`

# Report

### What unexpected behavior are you seeing?

The number of unread notifications on the app icon is not reduced when a user opens the received notification on iOS devices

### What is the expected behavior?

The number of notifications should be represented by an icon with the total number of notifications with the "Unread" status for the current user.

**Comment by rlepinski** [comment]
The badge is not supposed to reflect the number of notifications in the drawer, instead its supposed to be a reflection of updates that you have within the app, such as unread emails, new stories, etc...

With a bunch of custom work you could most likely keep the badge count in sync with the number of notifications, but it would require a dismiss notification category set on each notification, and to sync the count with the badge on that response, as well as when it opens. This is not a normal behavior though and there are probably cases where they will get out of sync due to not getting that dismiss callback.

**Comment by rlepinski** [comment]
When you say viewing incoming notifications do you mean message center messages? You need to add a listener for message center update and set the badge to the unread count (that is under the wrong key on iOS)

**Comment by dkulakov** [comment]
I'm talking about the badge on the app icon

https://github.com/urbanairship/react-native-airship/assets/6547279/2cb58942-1792-4a1b-9a59-63da27844609

**Comment by rlepinski** [comment]
What are you trying to reflect in the badge count? The notifications in the shade, or the pending unread messages in your message center?

**Comment by dkulakov** [comment]
I'm trying to understand how to manage the badge count on the app icon

https://github.com/urbanairship/react-native-airship/assets/6547279/ffdc1f41-36b9-4ea6-b6d1-6883b08a2cc6

**Comment by rlepinski** [comment]
I know, but what are you trying to tie it to? In the first video you open the notification, takes you to the message center, but you do not click a message so its still not read, so the count should stay the same?

Its usually not supposed to represent the notifications in the shade, but you can:
- Clear the badge when you launch the app
- Clear the badge when you show the message center in the app
- Tie the badge to number of unread messages in the message center in the app

If you are set on making it be tied to the number of notifications in the shade, we can try to figure it out but its not usually how the badge is supposed to work.

**Comment by rlepinski** [comment]
In the video above, how are you sending the notification? Are you including a badge value? Are you using auto badge? Is it sent with a message center message?

**Comment by rlepinski** [comment]
Your badge count is 0 (not set), you are then sending a +1 notification through APNs that results in a 1. It seems to be working as intended? 

I still having trouble understanding what you are trying to achieve.  What do you want the badge to reflect?

**Comment by dkulakov** [comment]
I wonder what I as a user have to do to make this badge disappear?

**Comment by rlepinski** [comment]
It depends on the app. You still need to clear the badge in the app by setting it to 0, or the unread count of the message center. Airship does not manage clearing the badge for you, just tracking the current value. If you use message center, we automatically set the badge on the notification to the unread count.

**Comment by dkulakov** [comment]
At best I need the behavior on android and ios to be the same or as similar as possible.
I recorded a [video](https://drive.google.com/file/d/1-b5NTMXyzPbmMI2BHlxAhH77OZZ__j9k/view?usp=share_link)

**Comment by rlepinski** [comment]
Badges are handled completely differently between the two OS versions. Android its a reflection of a notification in the shade, iOS is generally not that. I would suggest just setting the badge to 0 on app foreground on iOS for now

**Comment by dkulakov** [comment]
Hi @rlepinski , If I understand you correctly, this is not a limitation of airship, but of the ios OS itself, can I find this explanation in apple documentation?
