### ISSUE TITLE
[Android]: 'channelEditTags' overrides nothing

### ISSUE THREAD

**Issue by aurelbe** [urbanairship/react-native-module#528]
# Preliminary Info

### What Airship dependencies are you using?
@ua/react-native-airship: 16.1.0

# Report

### What unexpected behavior are you seeing?
I get the following error when trying to compile the app (new architecture is NOT enabled):
`e: /PROJECT_PATH/node_modules/@ua/react-native-airship/android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt: (164, 5): 'channelEditTags' overrides nothing`

### What is the expected behavior?
The app should compile

### What are the steps to reproduce the unexpected behavior?
- Add the Airship SDK to a project and try to build it

The relevant code is located here in your repo: https://github.com/urbanairship/react-native-airship/blob/cd6f0d1bbb526aeaf6b256863d8cb11eec245440/android/src/main/java/com/urbanairship/reactnative/AirshipModule.kt#L164
And you can see that there is no method called `channelEditTags` in the `AirshipSpec` class: https://github.com/urbanairship/react-native-airship/blob/main/android/src/oldarch/java/com/urbanairship/reactnative/AirshipSpec.kt

**Comment by rlepinski** [comment]
Will get it fixed today, thanks for the report.

**Comment by rlepinski** [comment]
Should be fixed in 16.1.1
