### ISSUE TITLE
Manage Delivered Notifications

### ISSUE THREAD

**Issue by AntiHate** [urbanairship/react-native-module#54]
It would be great if we could have access to delivered notifications (Notifications Panel). To remove specific or all notifications. Or should we look for another library for that? Thanks!

Edit: I found this [WIX React native notifications](https://github.com/wix/react-native-notifications) but it'd nice to use just one lib for notifications.

![image](https://user-images.githubusercontent.com/2887867/32425885-5a0da5b4-c2d8-11e7-9ab1-b13a87e5b1ec.png)

**Comment by rlepinski** [comment]
@AntiHate Remove all notifications is really easy, exposing individual notifications is a little harder. What APIs are you looking for?

**Comment by rlepinski** [comment]
The API you provided is only offered for iOS 10+. The same API on Android can almost be achieved with API 23+, but accessing the original payload would be difficult for notifications posted outside of Urban Airship. 

https://developer.android.com/reference/android/app/NotificationManager.html#getActiveNotifications()

**Comment by AntiHate** [comment]
Hi @rlepinski , Thankyou for your response. Right now I just need to cancel all the delivered notifications but it'd be great if we could get access to all delivered notifications data on both platforms so I'd able to remove specific notifications.

**Comment by AntiHate** [comment]
Do you plan to offer Local Notifications API? or this is something out of this project scope?

**Comment by AntiHate** [comment]
Thankyou @rlepinski for considering this. I'll look for it in the next release.

**Comment by AntiHate** [comment]
@rlepinski You made it along with management support, that was quick 🥇 Thankyou so much!

**Comment by rlepinski** [comment]
@AntiHate We will probably release early next week. I still need to verify everything works properly on iOS.

**Comment by rlepinski** [comment]
Released in 1.3.0. Added:
- [clearNotification](https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#.clearNotification)
- [clearNotifications](https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#.clearNotifications)
- [getActiveNotifications](https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#.getActiveNotifications)

**Comment by AntiHate** [comment]
@rlepinski  You are the best. Thankyou so much!
