### ISSUE TITLE
Getting  Error while installing Pod File

### ISSUE THREAD

**Issue by lavarajallu** [urbanairship/react-native-module#55]
In my react-native Project i want to Integrate urban airship  module. I followed the procedure from your website. [https://docs.urbanairship.com/platform/react-native/]
First I installed and linked . **react-native install urbanairship-react-native**.Then now i tried to install the cocaopods.I tried pod init command, but i am unable to create the podfile and getting error like below.

`## Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.14.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f025a02cd07d05eb8d7b340cccc91d99f90d9dc8
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "HEADER_SEARCH_PATHS", found "\""
    #  -------------------------------------------
    #  				DEAD_CODE_STRIPPING = NO;
    #  				DEVELOPMENT_TEAM = E24SB49T85;
1020>  				HEADER_SEARCH_PATHS = "$(SRCROOT)/../node_modules/react-native/React/**""$(SRCROOT)/../node_modules/urbanairship-react-native/ios/UARCTModule";
       				                                                                        ^
    #  				INFOPLIST_FILE = Koopi/Info.plist;
    #  				IPHONEOS_DEPLOYMENT_TARGET = 9.3;
    #  -------------------------------------------

/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:198:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:192:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.5.1/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.2/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.3.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22HEADER_SEARCH_PATHS%22%2C+found+%22%5C%22%22%0A++++%23++-------------------------------------------%0A++++%23++%09%09%09%09DEAD_CODE_STRIPPING+%3D+NO%3B%0A++++%23++%09%09%09%09DEVELOPMENT_TEAM+%3D+E24SB49T85%3B%0A1020%3E++%09%09%09%09HEADER_SEARCH_PATHS+%3D+%22%24%28SRCROOT%29%2F..%2Fnode_modules%2Freact-native%2FReact%2F%2A%2A%22%22%24%28SRCROOT%29%2F..%2Fnode_modules%2Furbanairship-react-native%2Fios%2FUARCTModule%22%3B%0A+++++++%09%09%09%09++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++%5E%0A++++%23++%09%09%09%09INFOPLIST_FILE+%3D+Koopi%2FInfo.plist%3B%0A++++%23++%09%09%09%09IPHONEOS_DEPLOYMENT_TARGET+%3D+9.3%3B%0A++++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Dictionaries
   https://github.com/suttacentral/suttacentral/issues/98 [open] [7 comments]
   29 Feb 2016

 - Alert if dictionary file is missing
   https://github.com/harleygn/WordsWithChilwell/issues/19 [open] [0 comments]
   a week ago

 - update gettext dictionaries
   https://github.com/facundoolano/advenjure/issues/44 [open] [1 comment]
   a week ago

and 28844 more at:
https://github.com/cocoapods/cocoapods/search?q=[!]%20Dictionary%20missing%20';'%20after%20key-value%20pair%20for%20%22HEADER_SEARCH_PATHS%22,%20found%20%22%5C%22%22%0A%20%20%20%20%23%20%20-------------------------------------------%0A%20%20%20%20%23%20%20%09%09%09%09DEAD_CODE_STRIPPING%20=%20NO;%0A%20%20%20%20%23%20%20%09%09%09%09DEVELOPMENT_TEAM%20=%20E24SB49T85;%0A1020%3E%20%20%09%09%09%09HEADER_SEARCH_PATHS%20=%20%22$(SRCROOT)/../node_modules/react-native/React/**%22%22$(SRCROOT)/../node_modules/urbanairship-react-native/ios/UARCTModule%22;%0A%20%20%20%20%20%20%20%09%09%09%09%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%0A%20%20%20%20%23%20%20%09%09%09%09INFOPLIST_FILE%20=%20Koopi/Info.plist;%0A%20%20%20%20%23%20%20%09%09%09%09IPHONEOS_DEPLOYMENT_TARGET%20=%209.3;%0A%20%20%20%20%23%20%20-------------------------------------------%0A&type=Issues&utf8=✓
STELLENTs-Mac-mini-4:ios stellent$ cd /Users/stellent/Documents/KoopiCustomer/ios `

**Comment by rlepinski** [comment]
What version of react are you using?

**Comment by lavarajallu** [comment]
"react": "16.0.0-alpha.12",
    "react-native": "0.46.1",

**Comment by rlepinski** [comment]
@lavarajallu it looks like something went wrong with the link step, you will need to modify your header search path to insert a `;` in the pbxproj file.
