### ISSUE TITLE
iOS: app crash on takeOff

### ISSUE THREAD

**Issue by fryossi** [urbanairship/react-native-module#61]
**Error:** 
CoreData: error:  Cannot load NSManagedObjectModel.  nil is an illegal URL parameter
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**stacktrace**: 
`dispatch_once(&takeOffPred_, ^{
        [UAirship executeUnsafeTakeOff:[config copy]];
    });`

`[UAirship takeOff:[UAConfig defaultConfig]];`

`[UAirship takeOff];`

`+(void)performTakeOff:(NSNotification *)notification {...}`

---------

Enterprise iOS certificate & provisioning.

pod 'UrbanAirship-iOS-SDK', '~>8.3'

"urbanairship-react-native": "1.2.2"
"react": "16.0.0-alpha.6"
"react-native": "0.44.3"

**EDIT:** 
UrbanAirship-iOS-SDK (8.6.0) (Podfile.lock).
The app crashes on every initialization.

**Comment by rlepinski** [comment]
What version of the UA SDK does your podfile.lock say?

**Comment by fryossi** [comment]
See **EDIT**. Thanks.

**Comment by rlepinski** [comment]
@fryossi Seems like a pod install problem. Could you try upgrading pods and see if that resolves the issue? If not, could you provide more info on if it use to work, and if so, what changed to break it?

**Comment by fryossi** [comment]
I have Multiple build configuration. All the other builds works fine.
The problem is on the Enterprise build. It uses a different Team, Certificate, and entitlements file (Enterprise program- without ApplePay). It can be launched locally (in dev mode) also i can archive and export for in house BUT it crashes every time.

**Comment by BrianBatchelder** [comment]
We think our resource bundle is missing from your IPA. Can you please check? Can you also verify that it runs correctly in dev mode, and that the crash is only occurring with your release version?

**Comment by fryossi** [comment]
You were right! I couldn't find the resources in the ipa file.
I had to `pod install` after adding the new build configuration. 
Thanks!

**Comment by rlepinski** [comment]
Glad its working!
