### ISSUE TITLE
Getting  urbanairship-react-native:unspecified

### ISSUE THREAD

**Issue by lavarajallu** [urbanairship/react-native-module#62]
iOS working fine But When i was  run in android application getting errorLike this

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':urbanairship-react-native'.
      > Could not resolve all dependencies for configuration ':urbanairship-react-native:_debugPublishCopy'.
         > Could not find any version that matches com.facebook.react:react-native:[0.40,).
           Versions that do not match:
               0.20.1
               0.20.0
               0.19.1
               0.19.0
               0.18.0
               + 12 more
           Required by:
               Koopi Customer:urbanairship-react-native:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by rlepinski** [comment]
Its unable to find a proper react version. Make sure you update your node modules and have the react maven repo listed in your build.gradle file. If you continue to have issues, please contact support.
