### ISSUE TITLE
Loading images from the message center

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#66]
Hi
Im using 
UrbanAirship.setAutoLaunchDefaultMessageCenter(false);

and then UrbanAirship.getInboxMessages()

But the object does not seem to contain any images if the message has one. We just see a key with the item 'Image'

is this the correct behaviour.

Thanks in advance.

**Comment by rlepinski** [comment]
Looks like we are not passing it down when mapping a message to a json object. We will fix in the next release.

**Comment by digitalhobo** [comment]
Thanks You. 👍

**Comment by rlepinski** [comment]
@digitalhobo Looks like we have it listed under `listIconUrl`, can you check that?

**Comment by rlepinski** [comment]
Closing. I think this is already supported.
