### ISSUE TITLE
Notifications with Web Page opens in browser after update to 1.3.1

### ISSUE THREAD

**Issue by santoslucas** [urbanairship/react-native-module#69]
We send notifications to our users with Web Pages. To avoid the browser to be opened instead of our own app, we configured a predicate in Android:

```
ActionRegistry.Predicate routeOpenUrlPredicate = new ActionRegistry.Predicate() {
    @Override
    public boolean apply(ActionArguments arguments) {
      return false;
    }
  };

UAirship.shared().getActionRegistry().getEntry(OpenExternalUrlAction.DEFAULT_REGISTRY_NAME).setPredicate(routeOpenUrlPredicate);
```

This was working until we updated the react-native-module to version 1.3.1. Since we made this change the expected behavior happens only when the app is running in background. If this is not the case, the browser is opened together with the app and after close the browser the app is visible.

Can you help?

**Comment by rlepinski** [comment]
@santoslucas where are you disabling the action?

**Comment by santoslucas** [comment]
I am disabling it in the `getPackages()` in MainApplication, after `new ReactAirshipPackage()` is called.

**Comment by rlepinski** [comment]
Thats probably the issue. `getPackages()` is not a lifecycle method. I doubt it gets called unless that app is foregrounding. Try to move the call into `onCreate()`

**Comment by santoslucas** [comment]
I moved it to `onCreate()` but now an exception is thrown:
```
java.lang.RuntimeException: Unable to create application com.xxx.MainApplication: java.lang.IllegalStateException: Take off must be called before shared()
```

**Comment by rlepinski** [comment]
Are you calling it before or after `super.onCreate();`? Make sure its after. If its still not working, it seems the plugin might not have been installed properly. You may want to remove it and install it again.

**Comment by santoslucas** [comment]
I am calling after `super.onCreate();`.

I'll try to remove the plugin and install it again.

**Comment by rlepinski** [comment]
If that still does not work, then you can add a call `Autopilot.automaticTakeOff(this);` before calling `UAirship.shared()` in `onCreate()`. However it should not be required.

**Comment by santoslucas** [comment]
I reinstalled, but still did not work as expected. Adding `Autopilot.automaticTakeOff(this);` before calling `UAirship.shared()` in `onCreate()` solved the problem.

Thank you.

**Comment by rlepinski** [comment]
Glad its working.
