### ISSUE TITLE
Install without linking the library natively

### ISSUE THREAD

**Issue by AdrianZghibarta** [urbanairship/react-native-module#71]
Hello guys, one question that is actually very blocking for me,
When I am running `react-native install urbanairship-react-native` the native link is done automatically and my Xcode project will not open any more:
```
john$ react-native install urbanairship-react-native
Scanning 640 folders for symlinks in /Users/john/Documents/projects/my_project/node_modules (6ms)
npm WARN eslint-plugin-redux-saga@0.4.0 requires a peer of eslint@^3.19.0 but none was installed.

+ urbanairship-react-native@1.4.0
removed 1 package and updated 1 package in 4.847s
Scanning 640 folders for symlinks in /Users/john/Documents/projects/my_project/node_modules (6ms)
rnpm-install info Linking urbanairship-react-native android dependency 
rnpm-install info Android module urbanairship-react-native has been successfully linked 
rnpm-install info Linking urbanairship-react-native ios dependency 
rnpm-install info iOS module urbanairship-react-native has been successfully linked 
rnpm-install info Module urbanairship-react-native has been successfully installed & linked
```

And after that I cannot open my Xcode project. Can I perform an install without linking the library natively? If yes, where can I find the instructions for that?

**Comment by rlepinski** [comment]
What Xcode version and react version are you using? Have not tested this, but to install manully I believe you just have to do these two steps:
```
npm install urbanairship-react-native --save
Drag node_modules/urbanairship-react-native/ios/UARCTModule.xcodeproj into your project
``` 
Then follow the rest of the steps in the README

**Comment by we4ce** [comment]
Hi, 
is there a way to link this manually in Android?
For now I have the iOS setup ok but on the Android get the message (see attachment).
![screen shot 2018-02-15 at 2 43 41 pm](https://user-images.githubusercontent.com/12914961/36257598-378eef2a-1260-11e8-87e6-bffb0195f31e.png)
 

in setting.gradle I have included:
```
include ':urbanairship-react-native'
project(':urbanairship-react-native').projectDir = new File(rootProject.projectDir, '../node_modules/urbanairship-react-native/android')
```


also in build.gradle:

```
compile 'com.urbanairship.android:urbanairship-sdk:9.0.+'
compile 'com.google.android.gms:play-services-gcm:11.8.0'
compile 'com.google.android.gms:play-services-location:11.8.0'
```

please advice

**Comment by crow** [comment]
I believe all you have to do is the following:

`npm install urbanairship-react-native --save
 Integrate source at node_modules/urbanairship-react-native/android
`
How you integrate the source is up to you, you can do this by manually adding the source as a package and merging the manifest items, or potentially by generating and linking [an AAR](https://developer.android.com/studio/projects/android-library.html).
