### ISSUE TITLE
Message Center content

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#72]
Helloo

Is their a method to get the Message Center content.

Thanks in advance.
:0)

**Comment by rlepinski** [comment]
Full docs are provided here: https://docs.urbanairship.com/reference/libraries/react-native/latest/UrbanAirship.html#.getInboxMessages

Message Center/Inbox/Rich Application Pages are all the various names for our message center product over the years. We decided to keep `inbox` as the api that powers our `message center`. If you are trying to build your own in react look for the inbox apis.

**Comment by digitalhobo** [comment]
Thank you 👍
