### ISSUE TITLE
IN-APP MESSAGE

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#73]
Hi

Should the IN-APP MESSAGE trigger an event when setAutoLaunchDefaultMessageCenter is set to false.

Thanks in advance
:0)

**Comment by rlepinski** [comment]
In-app messages are not related to message center. I understand the confusing as they are both technically a way to message the user in the app, but they are two different features.

**Comment by digitalhobo** [comment]
Thanks for the explanation. 
But if setAutoLaunchDefaultMessageCenter is set to true and you tap the in app notification it opens the message in the message center.

I am right to say that it is the one that pops up at the bottom when the app comes into the foreground.

Thanks you for the quick response.

**Comment by rlepinski** [comment]
Yes, the banner looking things - https://docs.urbanairship.com/whats-new/2015-05-31-in-app-messaging/#main

**Comment by digitalhobo** [comment]
Yes, thats the one, if an IN-APP MESSAGE is included with the message center and setAutoLaunchDefaultMessageCenter is set to false, is it possible to listen to an event.
As I would like to show the message as an overlay.
UrbanAirship.displayMessage(id, true);
rather than goto the message center.

:0)

**Comment by rlepinski** [comment]
So you want an event for when either a push or an in-app message is interacted with that tells the app to display the in-app message?

**Comment by digitalhobo** [comment]
Yes, a push message works as expected.
When we tap a push message, that is associated with a message center message, the event "notificationResponse" is triggered, and the response object contains "_uamid" which seems to be the message center message "id"
which we can then use to open the message in an overlay.

UrbanAirship.displayMessage(response.notification.extras._uamid, true);

**Comment by rlepinski** [comment]
We will introduce a new event in 1.5 that will let you know to launch either the message or message center if setAutoLaunchDefaultMessageCenter is set to false. Then you can use that instead of `_uamid` extra.

**Comment by digitalhobo** [comment]
thanks 👍

**Comment by rlepinski** [comment]
Have a PR up for the work. Going to expose a "showInbox" event that contains the optional message ID. Will only be emitted if setAutoLaunchDefaultMessageCenter is false.

**Comment by rlepinski** [comment]
@digitalhobo Released in 1.5.0
