### ISSUE TITLE
Breaking changes in  UrbanAirship-iOS-SDK (9.0.1)

### ISSUE THREAD

**Issue by listicos** [urbanairship/react-native-module#74]
Hello there are some breaking changes in 9.0.1 version so I think you should change this:

`[[UAirship defaultMessageCenter] display];`
to
`[[UAirship messageCenter] display];`

In the 1.4.0 version.

Thank you

**Comment by rlepinski** [comment]
Thanks for the report. We must of missed something during a commit. https://github.com/urbanairship/react-native-module/pull/75

**Comment by rlepinski** [comment]
Fixed in 1.4.1

**Comment by digitalhobo** [comment]
It might be worth mentioning in the docs to use
pod 'UrbanAirship-iOS-SDK', '~>9.0'

which is only compatible with Deployment Target 9
