### ISSUE TITLE
Get the Device Token in iOS

### ISSUE THREAD

**Issue by listicos** [urbanairship/react-native-module#79]
Hello, I don't find a way to get the device token once I hace the permissions.
I tried with this 
UrbanAirship.addListener('register', (event) => {
      console.log(event)
    })
In Objective C you can get the device token here
didRegisterForRemoteNotificationsWithDeviceToken

Thanks

**Comment by rlepinski** [comment]
Its part of that event but under the key `registrationToken`

**Comment by rlepinski** [comment]
In 1.5.0 we can expose a method to get the registrationToken/device token

**Comment by listicos** [comment]
The problem is, never firing the event once I get the permissions.

**Comment by rlepinski** [comment]
The device token does not need the permission prompt to generate starting with iOS 9 as long as you have background refresh enabled in your targets capabilities. The event probably already fired by that time.
