### ISSUE TITLE
UARCTModule - ARC Semantic issue - no known class method for selector 'messageCenter'

### ISSUE THREAD

**Issue by mixophrygian** [urbanairship/react-native-module#81]
Hi there,

Thanks for this module!  I'm getting a persistent build failure that I wonder if anyone has seen before.

I'm migrating away from react-native-ua (0.1.2) (followed all the steps [here](https://github.com/urbanairship/react-native-module/blob/master/ReactNativeUAMigration.md#ios-react-native-ua-removal) for removing references to the old module) to urbanairship-react-native (version 1.4.2)

Then followed the iOS installation steps [here](https://docs.urbanairship.com/platform/react-native/) exactly.

Currently running: 

react-native-cli 2.0.1
react-native 0.53.3
Xcode 9.2.

After Cleaning and Building, I get two errors within UARCTMessageCenter.m, `No known class method for selector 'messageCenter'`.

<img width="871" alt="screen shot 2018-02-21 at 6 25 23 pm" src="https://user-images.githubusercontent.com/7801376/36516834-9cba0afa-1734-11e8-84bd-8ca9e44c9d18.png">

Possibly related, warning in the same module - `warning: ignoring recursive header expansion for path '/**'`

**Comment by crow** [comment]
In the sample podfile you'll want to include either:
`pod 'UrbanAirship-iOS-SDK', '~>9.0.0'
`
or 
`pod 'UrbanAirship-iOS-SDK'
`

and be sure to run: 
`pod update`

**Comment by mixophrygian** [comment]
That fixed it, thank you!

**Comment by mixophrygian** [comment]
Where would I submit a PR to update the version in the documentation? 

https://docs.urbanairship.com/platform/react-native/#ios

**Comment by crow** [comment]
Our external documentation builds from a private repo - but the instruction you mention will be updated in the next day or so. Thanks for the offer!
