### ISSUE TITLE
NamedUser 

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#82]
Hello

Is their any way of unsetting the named user.

I have a scenario where user A logs in, a named user is set based on their id.
I then log in with a new user with a different user B, and user B can see user A's messages.

This still occurs If I setNamedUser to an empty string when logging out.

Thanks in advance.

**Comment by crow** [comment]
To dissociate a named user in Android - the named user value must be null. [More information.](https://github.com/urbanairship/android-library/blob/fbfbcde094cca307cfd2906a508d4262546d2e37/urbanairship-sdk/src/main/java/com/urbanairship/push/NamedUser.java#L144). This is something we can do in the bindings in the same way that we do in iOS. Thanks for bringing this to our attention.
