### ISSUE TITLE
Push notification text is empty on Android

### ISSUE THREAD

**Issue by jrbaldwin** [urbanairship/react-native-module#83]
When I try sending a push notification from the Urban Airship dashboard, I do get an app notification on Android, but the notification message text is empty.

When I tap the notification it opens the correct app.

In logcat, I see the message content text that should be displaying in the push notification: HELLO THIS IS A TEST NOTIFICATION

```
ReactNativeNotifs: New message from GCM: Bundle[{com.urbanairship.push.ALERT=HELLO THIS IS A TEST NOTIFICATION, google.sent_time=1518420400840, google.ttl=2419200, com.urbanairship.push.PUSH_ID=<hidden>, google.message_id=<hidden>, com.urbanairship.push.APID=<hidden>, com.urbanairship.push.CANONICAL_PUSH_ID=<hidden>}]

I Spot - UALib: Received push: {google.sent_time=1518420400840, com.urbanairship.push.PUSH_ID=<hidden>, com.urbanairship.push.CANONICAL_PUSH_ID=<hidden>, com.urbanairship.push.ALERT=HELLO THIS IS A TEST NOTIFICATION, com.urbanairship.push.APID=<hidden>, google.ttl=2419200, google.message_id=<hidden>}
V NotificationService: pkg=com.myapp canInterrupt=false intercept=true
```

**Comment by crow** [comment]
Are you currently using a custom notification factory as outlined [here](https://docs.urbanairship.com/platform/android/#customizing-push-notifications)?

**Comment by jrbaldwin** [comment]
No, I'm using the default notification factory.

On Mar 1, 2018 03:29, "David Crow" <notifications@github.com> wrote:

Are you currently using a custom notification factory as outlined here
<https://docs.urbanairship.com/platform/android/#customizing-push-notifications>
?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/urbanairship/react-native-module/issues/83#issuecomment-369335735>,
or mute the thread

**Comment by crow** [comment]
Could I get the following?:
-Screenshot
-Device type
-OS version
-Plugin Version

Thanks!
