### ISSUE TITLE
Named User and Alias

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#89]
Hi
Is see that their is a method to set the named user.
Is their also a possibility to set alias, as were migrating from an old app a system that our client uses still sends notifications to users alias.

Or is it a case that if they still send notifications to alias that it will automatically push to a named user.

Thanks in advance.

**Comment by rlepinski** [comment]
Alias is deprecated so I am hesitant to provide bindings in the SDK, however it would be a bummer if it blocked you. I do not believe sending to alias automatically sends to named user, but our support team might be able to help with migrations. Could you please contact support?

**Comment by digitalhobo** [comment]
Thank You for getting back so promptly. 
We will contact support. 👍
