### ISSUE TITLE
Add Carthage option

### ISSUE THREAD

**Issue by eugenehp** [urbanairship/react-native-module#9]
Cocoapod is good, but would be great to have Carthage option in here:
https://github.com/urbanairship/ios-library#carthage

**Comment by rlepinski** [comment]
We will look into this in the next release. I think we just need to modify some search paths to make it work with both cocoapods and carthage.

**Comment by eugenehp** [comment]
@rlepinski Ryan, sounds good, thanks. Basically it's about adding proper headers and references inside search paths inside Xcode settings. I did relevant changes, but it's not PR ready yet – https://github.com/eugenehp/react-native-module/commit/a272da4f57bf3256d95759df29647e2495bd0f2e

another thing I wanted to ask, is an ability to execute configuration of the module inside JS, this way we can reuse environment settings inside JS VM.
Let me know your thoughts on this.

Thanks.

**Comment by rlepinski** [comment]
@eugenehp You mean being able to configure UAirship from JS? The main issue with that is UAirship needs to be ready before application:didFinishLaunching: on iOS and in the Application (background start) on Android.

What we have done in other plugins is allow the initial config to be done at a later time and automatically use those settings on subsequent launches. If that method gets called again with different values UAirship will continue to use the old values until the next launch.

Totally possible but its not the most ideal setup.

**Comment by eugenehp** [comment]
@rlepinski thanks for the feedback, looks like I'll need to think more on this.

**Comment by rlepinski** [comment]
@eugenehp Added Carthage support. We have a ticket in our backlog to enable takeoff from JS, will be released in a future version. Closing this for now since it was initially for carthage support.
