### ISSUE TITLE
Scenario

### ISSUE THREAD

**Issue by digitalhobo** [urbanairship/react-native-module#96]
We have a scenario where a user logs into our app, the named user is set and UA is enabled.
The device receives a message center inbox notification that is sent to all devices.

When the user logs out and logs in with a different user, they still see the message in the message center. Is this the correct behaviour.

Thanks

**Comment by rlepinski** [comment]
@digitalhobo message center is currently tied to the device, not a named user. The behavior you are experiencing is correct. Please request that capability by contacting our support team. 

I might be able to help with a workaround for you. How are you sending the messages? Unicast? If so, you can add the named user as an extra and filter on the listing for the current logged in user.

**Comment by digitalhobo** [comment]
Ok, thanks for the info. 👍
