### ISSUE TITLE
Push notifications not enable on some devices

### ISSUE THREAD

**Issue by Diego-Franco** [urbanairship/react-native-module#99]
I'm building and app with the react native module, I'm trying to enable push notifications for my app.

Devices: Samsung galaxy S6 (7.0) , Samsung Galaxy On 5 (6.0.1)

Steps:
 - Open the app
 - Login with a valid user
 - getting channel id and register on the server
 - success registrations
 
Expectation: 
 - push notifications enable

 Result:
 - Galaxy On 5 is working fine, without any problems
 - Galaxy S6 is not getting notifications 

More: 
  - Actually when I use this `UrbanAirship.isUserNotificationsOptedIn()` the result is false for the Galaxy S6, so I'm not sure if is related with Samsung issue with android 7 or something else is happening
 - My previous app is Android native and is working fine in the Galaxy S6, so I'm not sure why the react native module is not

**Comment by rlepinski** [comment]
Are you enabling user notifications ? What OS versions? Did you disable notifications at the app level? Settings -> App Info -> App -> Notifications ?

**Comment by Diego-Franco** [comment]
Yes, and yes, I did all the steps for notifications, the OS versions is pointed in the issue, for the Galaxy S6 is `Android 7.0` and for the galaxy On 5 is `Android 6.0.1`

and like I said, my previous native android app is working fine on the Galaxy S6

**Comment by rlepinski** [comment]
This is running the same SDK that runs on a native app.

Here is the call that determines that opt in status:
https://github.com/urbanairship/android-library/blob/fbfbcde094cca307cfd2906a508d4262546d2e37/urbanairship-sdk/src/main/java/com/urbanairship/push/PushManager.java#L544

Things that could cause it to be opted out:
- User notifications disabled on PushManager
- Push disabled on PushManager
- GCM/FCM is unable to register
- Notifications are disabled at the app level
- Google Play Services is out of date

Assuming its the same code running on both phones, you can probably rule out push and user notifications being disabled on the SDK.  My guess its most likely Google Play Services being out of date. Your react version is probably pulling in a newer version of the Play Services than your native app.

You should see something in the logs during start up. You can also add 
```
import com.urbanairship.google.PlayServicesUtils;
...

public class MainActivity extends ReactActivity {
    ...

    @Override
    public void onResume() {
        super.onResume();

        // Handle any Google Play services errors
        if (PlayServicesUtils.isGooglePlayStoreAvailable(this)) {
            PlayServicesUtils.handleAnyPlayServicesError(this);
        }
}
```

To the MainActivity.java to have it prompt the user to install latest version.

**Comment by Diego-Franco** [comment]
Thanks for your help, I forgot about Play services, and I just updated the Google play services and works, I'm going to put this check in the native code.
